import Link from "next/link";
import Header from "../../../components/layout/Header";
import { bibleBooks } from "../../../content/bible/books";
import { deepBookMap } from "../../../content/bible/deep";

export function generateStaticParams() {
  return Object.keys(deepBookMap).map(book => ({ book }));
}

export default async function DeepBookPage({ params }: { params: Promise<{ book: string }> }) {
  const { book: slug } = await params;
  const book = bibleBooks.find(b => b.slug === slug);
  const guide = deepBookMap[slug];
  if (!book || !guide) return <div className="shell"><Header/><main className="mx-auto max-w-3xl px-6 py-24"><h1 className="text-4xl font-semibold">Deep guide not found</h1><Link className="sans mt-6 inline-block text-sm font-bold text-[var(--accent)]" href="/bible">Return to Bible Explorer →</Link></main></div>;

  return <div className="shell"><Header/><main className="mx-auto max-w-[1220px] px-5 py-10 sm:px-6 sm:py-14">
    <div className="sans flex flex-wrap items-center gap-2 text-xs font-bold text-[var(--muted)]"><Link href="/bible">Bible</Link><span>/</span><span className="text-[var(--accent)]">{book.name}</span></div>
    <header className="mt-8 max-w-5xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Deep Book Guide · {book.testament}</p><h1 className="mt-3 text-5xl font-semibold leading-tight sm:text-6xl">{guide.name}</h1><p className="mt-4 text-2xl leading-9 text-[var(--muted)]">{guide.subtitle}</p><p className="mt-6 max-w-4xl text-lg leading-8 text-[var(--muted)]">{guide.overview}</p></header>
    <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]">
      <article className="space-y-7">
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Book profile</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><h2 className="text-lg font-semibold">Genre</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{guide.genre}</p></div><div><h2 className="text-lg font-semibold">Historical setting</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{guide.setting}</p></div><div><h2 className="text-lg font-semibold">Authorship</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{guide.authorship}</p></div><div><h2 className="text-lg font-semibold">Dating</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{guide.dating}</p></div></div></section>
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Book structure</p><div className="mt-5 space-y-3">{guide.structure.map(s=><div key={s.title} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-lg font-semibold">{s.title}</h2><span className="sans text-xs font-bold text-[var(--accent)]">Ch. {s.chapters}</span></div><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{s.description}</p></div>)}</div></section>
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">People, places & themes</p><div className="mt-5 grid gap-6 md:grid-cols-3"><div><h2 className="font-semibold">People</h2><div className="mt-2 flex flex-wrap gap-2">{guide.majorPeople.map(x=><span key={x} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div><div><h2 className="font-semibold">Places</h2><div className="mt-2 flex flex-wrap gap-2">{guide.majorPlaces.map(x=><span key={x} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div><div><h2 className="font-semibold">Themes</h2><div className="mt-2 flex flex-wrap gap-2">{guide.majorThemes.map(x=><span key={x} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div></div></section>
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Historical questions</p><div className="mt-4 space-y-3">{guide.historicalQuestions.map(q=><div key={q} className="rounded-2xl bg-[var(--surface-2)] p-4 text-sm leading-6 text-[var(--muted)]">{q}</div>)}</div></section>
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Study principles</p><div className="mt-4 space-y-3">{guide.studyNotes.map(n=><p key={n} className="text-base leading-8 text-[var(--muted)]">{n}</p>)}</div></section>
        <section className="panel rounded-3xl p-6 sm:p-9"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Chapter-by-chapter guide</p><h2 className="mt-2 text-3xl font-semibold">Explore all {book.chapters} chapters</h2></div><Link href={`/bible?book=${book.slug}`} className="sans text-sm font-bold text-[var(--accent)]">Chapter grid →</Link></div><div className="mt-6 space-y-4">{guide.chapters.map(ch=><Link key={ch.number} href={`/bible/${book.slug}/${ch.number}`} className="block rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-5 transition hover:-translate-y-0.5 hover:border-[var(--accent)]"><div className="flex flex-wrap items-baseline justify-between gap-3"><h3 className="text-xl font-semibold">{ch.number}. {ch.title}</h3><span className="sans text-xs font-bold text-[var(--accent)]">Open chapter →</span></div><p className="mt-2 text-sm leading-7 text-[var(--muted)]">{ch.summary}</p><div className="mt-3 flex flex-wrap gap-2">{ch.themes.map(t=><span key={t} className="sans rounded-full bg-[var(--surface)] px-2.5 py-1.5 text-[11px] font-semibold text-[var(--muted)]">{t}</span>)}</div></Link>)}</div></section>
      </article>
      <aside className="space-y-4 lg:sticky lg:top-24 lg:h-fit"><div className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--muted)]">Canonical status</p>{Object.entries(guide.canon).map(([k,v])=><div key={k} className="mt-4 border-b border-[var(--border)] pb-4 last:border-0"><p className="sans text-xs font-bold uppercase tracking-wider text-[var(--accent)]">{k.replaceAll("-"," ")}</p><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{v}</p></div>)}</div><div className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--muted)]">Study mode</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Read the chapter summary first, then investigate its people, places, evidence and historical questions. Full Bible text remains external.</p><a href={`https://www.biblegateway.com/passage/?search=${encodeURIComponent(book.name)}&version=NRSVUE`} target="_blank" rel="noreferrer" className="sans mt-4 inline-flex rounded-xl bg-[var(--accent)] px-4 py-3 text-xs font-bold text-white">Open full book externally ↗</a></div><Link href="/canon" className="block rounded-3xl bg-[var(--surface-2)] p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Compare traditions</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">See how Protestant, Catholic, Orthodox and other traditions organize and receive Scripture.</p></Link></aside>
    </div>
  </main></div>;
}
