import Link from "next/link";
import Header from "../../../components/layout/Header";
import { placeMap, places } from "../../../content/places";
import { personMap } from "../../../content/people";
import { storyMap } from "../../../content/stories";

export function generateStaticParams(){return places.map(p=>({slug:p.slug}));}
export default async function PlacePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const place=placeMap[slug];
 if(!place)return <div className="shell"><Header/><main className="mx-auto max-w-3xl px-6 py-24"><h1 className="text-4xl font-semibold">Place not found</h1><Link href="/places" className="sans mt-6 inline-block font-bold text-[var(--accent)]">← Return to atlas</Link></main></div>;
 const people=place.people.map(s=>personMap[s]).filter(Boolean); const stories=place.storySlugs.map(s=>storyMap[s]).filter(Boolean);
 return <div className="shell"><Header/><main className="mx-auto max-w-[1180px] px-5 py-10 sm:px-6 sm:py-14">
   <div className="sans flex flex-wrap gap-2 text-xs font-bold text-[var(--muted)]"><Link href="/places">Places</Link><span>/</span><span className="text-[var(--accent)]">{place.name}</span></div>
   <div className="mt-5"><Link href={`/connections?focus=place:${place.slug}`} className="sans inline-flex rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-2 text-sm font-bold hover:border-[var(--accent)]">Explore connections →</Link></div>
    <header className="mt-8 max-w-4xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">{place.type} · {place.region}</p><h1 className="mt-3 text-5xl font-semibold leading-tight sm:text-6xl">{place.name}</h1><p className="mt-5 text-xl leading-9 text-[var(--muted)]">{place.summary}</p></header>
   <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_310px]"><article className="space-y-6">
    <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Biblical significance</p><p className="mt-4 text-lg leading-8">{place.biblicalSignificance}</p></section>
    <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Historical significance</p><p className="mt-4 text-lg leading-8 text-[var(--muted)]">{place.historicalSignificance}</p></section>
    <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Archaeology & evidence</p><p className="mt-4 text-lg leading-8 text-[var(--muted)]">{place.archaeology}</p></section>
    {people.length?<section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">People connected to this place</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{people.map((p:any)=><Link key={p.slug} href={`/people/${p.slug}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4 hover:border-[var(--accent)]"><h3 className="font-semibold">{p.name}</h3><p className="mt-1 text-sm text-[var(--muted)]">{p.role}</p></Link>)}</div></section>:null}
    {stories.length?<section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Related encyclopedia</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{stories.map((s:any)=><Link key={s.slug} href={`/story/${s.slug}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4 hover:border-[var(--accent)]"><h3 className="font-semibold">{s.title}</h3><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{s.summary??s.subtitle??"Open article →"}</p></Link>)}</div></section>:null}
   </article><aside className="space-y-4 lg:sticky lg:top-24 lg:h-fit"><div className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--muted)]">Quick facts</p><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-bold">Region</dt><dd className="text-[var(--muted)]">{place.region}</dd></div><div><dt className="font-bold">Era</dt><dd className="text-[var(--muted)]">{place.era}</dd></div><div><dt className="font-bold">Coordinates</dt><dd className="text-[var(--muted)]">{place.coordinates.lat.toFixed(4)}, {place.coordinates.lon.toFixed(4)}</dd></div></dl></div><div className="panel-muted rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Bible references</p><div className="mt-3 flex flex-wrap gap-2">{place.bibleReferences.map(r=><span key={r} className="sans rounded-full bg-[var(--surface)] px-3 py-2 text-xs font-bold">{r}</span>)}</div></div><div className="panel-muted rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Themes</p><div className="mt-3 flex flex-wrap gap-2">{place.themes.map(t=><span key={t} className="sans rounded-full bg-[var(--surface)] px-3 py-2 text-xs font-bold">{t}</span>)}</div></div></aside></div>
 </main></div>;
}
