import Link from "next/link";
import Header from "../../components/layout/Header";
import { extendedScriptureBooks } from "../../content/extended/books";

export default function ExtendedScripturePage() {
  const families = ["Deuterocanonical","Textual addition","Orthodox","Ethiopian"] as const;
  return <div className="shell"><Header/><main className="mx-auto max-w-[1500px] px-4 py-10 sm:px-6">
    <header className="max-w-5xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Extended Scripture</p><h1 className="mt-3 text-5xl font-semibold leading-tight">Deuterocanonical, Orthodox & Ethiopian traditions</h1><p className="mt-5 text-lg leading-8 text-[var(--muted)]">A study library for books and textual traditions outside the Protestant 66-book core. These materials are not presented as one universal canon: each entry records the traditions in which it is received and its historical-literary significance.</p></header>
    <section className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{families.map(f=><article key={f} className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">{f}</p><h2 className="mt-2 text-xl font-semibold">{extendedScriptureBooks.filter(b=>b.family===f).length} entries</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{f === "Deuterocanonical" ? "Books received as deuterocanonical in Catholic and/or Orthodox traditions." : f === "Textual addition" ? "Additional material incorporated into books such as Esther and Daniel." : f === "Orthodox" ? "Material received or preserved in broader Eastern Christian collections, with status varying by tradition." : "Distinctive material associated with the Ethiopian Orthodox biblical tradition."}</p></article>)}</section>
    {families.map(f=><section key={f} className="mt-12"><div className="mb-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">{f}</p><h2 className="mt-2 text-3xl font-semibold">{f} library</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{extendedScriptureBooks.filter(b=>b.family===f).map(book=><Link key={book.slug} href={`/extended/${book.slug}`} className="panel rounded-3xl p-5 transition hover:-translate-y-0.5 hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-3"><span className="sans rounded-full bg-[var(--surface-2)] px-2.5 py-1 text-[11px] font-bold text-[var(--muted)]">{book.approximateStructure ?? "Structure varies"}</span><span className="sans text-[11px] font-bold text-[var(--accent)]">Explore →</span></div><h3 className="mt-4 text-xl font-semibold">{book.name}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{book.summary}</p><div className="mt-4 flex flex-wrap gap-2">{book.tradition.map(t=><span key={t} className="sans rounded-full border border-[var(--border)] px-2.5 py-1 text-[10px] font-bold">{t}</span>)}</div></Link>)}</div></section>)}
    <section className="mt-12 rounded-3xl bg-[var(--surface-2)] p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Research note</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">This library describes canonical and reception status rather than reproducing full copyrighted translations. Chapter counts and organization can differ between traditions and editions, so entries with unstable structures are deliberately labelled instead of forcing a single scheme.</p></section>
  </main></div>;
}
