import Link from "next/link";
import Header from "../../components/layout/Header";
import { kingdoms } from "../../content/kingdoms";

export default async function KingdomsPage({searchParams}:{searchParams?:Promise<{q?:string;era?:string}>}){
  const params=searchParams?await searchParams:{};
  const q=(params.q??"").trim().toLowerCase();
  const era=params.era??"All eras";
  const eras=["All eras",...Array.from(new Set(kingdoms.map(k=>k.era)))];
  const filtered=kingdoms.filter(k=>(!q||[k.name,k.type,k.region,k.capital,k.summary,k.historicalSignificance,...k.themes].join(" ").toLowerCase().includes(q))&&(era==="All eras"||k.era===era));
  return <div className="shell"><Header/><main className="mx-auto max-w-[1280px] px-5 py-10 sm:px-6 sm:py-14">
    <header className="max-w-4xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Political history</p><h1 className="mt-3 text-5xl font-semibold leading-tight sm:text-6xl">Kingdoms & Empires</h1><p className="mt-5 text-xl leading-9 text-[var(--muted)]">The political powers that shaped the Biblical world — from Egypt and the Late Bronze Age to Assyria, Babylon, Persia, the Hellenistic kingdoms and Rome.</p></header>
    <div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="panel rounded-2xl p-5"><p className="sans text-xs font-black uppercase tracking-widest text-[var(--muted)]">Entities</p><p className="mt-2 text-3xl font-semibold">{kingdoms.length}</p><p className="mt-1 text-sm text-[var(--muted)]">political entities</p></div><div className="panel rounded-2xl p-5"><p className="sans text-xs font-black uppercase tracking-widest text-[var(--muted)]">Layers</p><p className="mt-2 text-3xl font-semibold">Rulers · Wars · Evidence</p><p className="mt-1 text-sm text-[var(--muted)]">linked historical context</p></div><div className="panel rounded-2xl p-5"><p className="sans text-xs font-black uppercase tracking-widest text-[var(--muted)]">Perspective</p><p className="mt-2 text-3xl font-semibold">Bible + History</p><p className="mt-1 text-sm text-[var(--muted)]">tradition separated from external evidence</p></div></div>
    <form className="panel mt-10 grid gap-3 rounded-3xl p-4 sm:grid-cols-[1fr_240px_auto]" action="/kingdoms"><input name="q" defaultValue={params.q??""} placeholder="Search kingdoms, rulers, regions, capitals…" className="sans rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-3 text-sm outline-none focus:border-[var(--accent)]"/><select name="era" defaultValue={era} className="sans rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-3 text-sm">{eras.map(e=><option key={e}>{e}</option>)}</select><button className="sans rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-bold text-white">Filter</button></form>
    <p className="sans mt-5 text-sm font-semibold text-[var(--muted)]">Showing {filtered.length} of {kingdoms.length} political entities</p>
    <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(k=><Link key={k.slug} href={`/kingdoms/${k.slug}`} className="panel rounded-3xl p-5 transition hover:-translate-y-1 hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-3"><p className="sans text-[10px] font-black uppercase tracking-[.16em] text-[var(--accent)]">{k.era}</p><span className="sans rounded-full bg-[var(--surface-2)] px-2.5 py-1 text-[10px] font-bold text-[var(--muted)]">{k.type}</span></div><h2 className="mt-3 text-2xl font-semibold">{k.name}</h2><p className="sans mt-2 text-xs font-bold text-[var(--muted)]">{k.dates} · {k.capital}</p><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{k.summary}</p><div className="mt-4 flex flex-wrap gap-2">{k.themes.slice(0,3).map(t=><span key={t} className="sans rounded-full border border-[var(--border)] px-2.5 py-1 text-[10px] font-semibold text-[var(--muted)]">{t}</span>)}</div><span className="sans mt-5 block text-sm font-bold text-[var(--accent)]">Open political profile →</span></Link>)}</section>
  </main></div>
}
