export type Place = {
  slug: string;
  name: string;
  type: string;
  region: string;
  era: string;
  coordinates: { lat: number; lon: number };
  summary: string;
  biblicalSignificance: string;
  historicalSignificance: string;
  archaeology: string;
  bibleReferences: string[];
  people: string[];
  storySlugs: string[];
  themes: string[];
};

export const places: Place[] = [
  {slug:"jerusalem",name:"Jerusalem",type:"City",region:"Judah / Southern Levant",era:"Iron Age to Roman period",coordinates:{lat:31.7683,lon:35.2137},summary:"The major political, religious and symbolic centre of Judah and later the focus of Second Temple and early Christian history.",biblicalSignificance:"Jerusalem becomes David's royal centre, Solomon's temple city, the capital of Judah and the setting for major events in the Gospels and Acts.",historicalSignificance:"Its history can be traced through Iron Age Judah, Babylonian conquest, Persian Yehud, Hellenistic rule, Hasmonean expansion and Roman Judea.",archaeology:"Archaeology includes Iron Age fortifications and settlement remains, Second Temple-period structures and extensive evidence for the Roman-period city and its destruction in 70 CE.",bibleReferences:["2 Samuel 5","1 Kings 8","2 Kings 25","Matthew 21","Acts 2"],people:["david","solomon","hezekiah","josiah","jesus","peter","titus"],storySlugs:["david-captures-jerusalem","solomon-builds-temple","jerusalem-586","jerusalem-70"],themes:["Capital city","Temple","Exile","Second Temple","Early Christianity"]},
  {slug:"jericho",name:"Jericho",type:"City / Archaeological site",region:"Jordan Valley",era:"Neolithic to Iron Age",coordinates:{lat:31.8715,lon:35.4444},summary:"One of the ancient world's most important settlement sites, associated in the Bible with Joshua's entry into Canaan.",biblicalSignificance:"Joshua 6 describes the capture of Jericho, making the city central to the biblical conquest tradition.",historicalSignificance:"Jericho has an exceptionally long settlement sequence, making it valuable for studying the transition from mobile communities to permanent settlement.",archaeology:"Tell es-Sultan preserves multiple settlement phases. Dating and interpretation of the site's destruction layers remain central to debates over the historicity and chronology of the conquest account.",bibleReferences:["Joshua 2","Joshua 6","Matthew 20"],people:["joshua"],storySlugs:["jericho","jericho-site","crossing-the-jordan"],themes:["Conquest","Canaan","Neolithic settlement"]},
  {slug:"hazor",name:"Hazor",type:"City / Archaeological site",region:"Upper Galilee",era:"Bronze Age to Iron Age",coordinates:{lat:33.0172,lon:35.5697},summary:"A major northern Canaanite centre and later Israelite site whose destruction layers are important to biblical archaeology.",biblicalSignificance:"Hazor appears in Joshua and Judges and is described as a major Canaanite centre before Israelite control.",historicalSignificance:"The site demonstrates the scale and complexity of northern Levantine urbanism and later Israelite occupation.",archaeology:"Excavations at Tel Hazor have exposed monumental architecture, destruction layers, temples and administrative areas across several periods.",bibleReferences:["Joshua 11","Judges 4","1 Kings 9"],people:["joshua","deborah","solomon"],storySlugs:["hazor"],themes:["Canaanite cities","Israelite settlement","Archaeology"]},
  {slug:"lachish",name:"Lachish",type:"City / Archaeological site",region:"Shephelah of Judah",era:"Bronze Age to Iron Age",coordinates:{lat:31.5631,lon:34.8475},summary:"A major fortified Judean city whose Assyrian siege is unusually well documented by archaeology and imperial art.",biblicalSignificance:"Lachish was one of Judah's major fortified cities and was captured during Sennacherib's campaign.",historicalSignificance:"The site provides a rare convergence of biblical narrative, Assyrian royal inscriptions, reliefs and archaeological destruction evidence.",archaeology:"The siege ramp, destruction layer, Assyrian reliefs and excavated fortifications form a major evidence cluster for the 701 BCE campaign.",bibleReferences:["2 Kings 18","2 Chronicles 32","Isaiah 36"],people:["hezekiah","sennacherib"],storySlugs:["lachish","sennacherib"],themes:["Assyria","Siege warfare","Archaeology"]},
  {slug:"samaria",name:"Samaria",type:"City / Capital",region:"Northern Israel",era:"Iron Age to Roman period",coordinates:{lat:32.2761,lon:35.1903},summary:"Capital of the northern kingdom of Israel from the reign of Omri until its conquest by Assyria.",biblicalSignificance:"Samaria is the political centre of the northern kingdom and the setting for the fall of Israel in 722/721 BCE.",historicalSignificance:"The city's development reflects the emergence of the Omride dynasty and Israel's integration into wider Levantine politics.",archaeology:"Excavations have revealed monumental royal architecture and material culture from the Iron Age and later periods.",bibleReferences:["1 Kings 16","2 Kings 17"],people:["omri","ahab","jehu"],storySlugs:["samaria","omri","fall-samaria"],themes:["Northern kingdom","Omrides","Assyria"]},
  {slug:"megiddo",name:"Megiddo",type:"City / Archaeological site",region:"Jezreel Valley",era:"Bronze Age to Iron Age",coordinates:{lat:32.5851,lon:35.1826},summary:"A strategically positioned tell controlling routes through the Jezreel Valley and a key site for studying Canaanite and Israelite state formation.",biblicalSignificance:"Megiddo appears in accounts involving Solomon, the northern kingdom and Josiah's death.",historicalSignificance:"Its location made it important to successive regional powers, and its archaeological sequence spans millennia.",archaeology:"Excavations have uncovered monumental gates, palaces, water systems and destruction layers from multiple periods.",bibleReferences:["1 Kings 9","2 Kings 23"],people:["solomon","josiah"],storySlugs:["megiddo"],themes:["Trade routes","Kingdoms","Archaeology"]},
  {slug:"bethlehem",name:"Bethlehem",type:"Town",region:"Judah",era:"Iron Age to Roman period",coordinates:{lat:31.7054,lon:35.2024},summary:"A Judean town associated with David and, in the Gospel traditions, the birthplace of Jesus.",biblicalSignificance:"Bethlehem is David's ancestral town and is linked by Matthew and Luke with Jesus' birth traditions.",historicalSignificance:"The site lies within the central highlands south of Jerusalem and belongs to the settlement landscape of ancient Judah.",archaeology:"Archaeological evidence comes from the wider Bethlehem/Judah region and later monumental remains; direct identification of individual biblical events remains limited.",bibleReferences:["1 Samuel 16","Micah 5","Matthew 2","Luke 2"],people:["david","jesus"],storySlugs:["david","jesus"],themes:["Davidic dynasty","Jesus","Judah"]},
  {slug:"nazareth",name:"Nazareth",type:"Village / Town",region:"Galilee",era:"Second Temple to Roman period",coordinates:{lat:32.6996,lon:35.3035},summary:"The Galilean hometown associated with Jesus in the New Testament.",biblicalSignificance:"The Gospels repeatedly identify Jesus with Nazareth and Galilee.",historicalSignificance:"Nazareth was a small settlement within the rural Galilean landscape of the early Roman period.",archaeology:"Excavations in and around Nazareth have identified domestic, agricultural and burial evidence relevant to its Second Temple-period settlement context.",bibleReferences:["Matthew 2","Luke 1","Luke 4","John 1"],people:["jesus"],storySlugs:["jesus"],themes:["Galilee","Jesus","Second Temple"]},
  {slug:"capernaum",name:"Capernaum",type:"Village / Lakeside settlement",region:"Sea of Galilee",era:"Second Temple to Byzantine period",coordinates:{lat:32.8806,lon:35.5733},summary:"A Galilean lakeside settlement strongly associated with Jesus' ministry.",biblicalSignificance:"The Gospels describe Capernaum as a major base for Jesus' activity in Galilee.",historicalSignificance:"The settlement illustrates everyday life in Roman-period Galilee and the religious and economic networks around the Sea of Galilee.",archaeology:"Excavated domestic structures, a synagogue complex and later Christian remains illuminate the site's development.",bibleReferences:["Matthew 4","Mark 1","Luke 7","John 6"],people:["jesus","peter"],storySlugs:["capernaum"],themes:["Galilee","Jesus","Synagogue"]},
  {slug:"caesarea-maritima",name:"Caesarea Maritima",type:"Port city",region:"Mediterranean coast",era:"Hellenistic to Late Antique",coordinates:{lat:32.5009,lon:34.8918},summary:"A major Herodian port and Roman administrative centre on the Mediterranean coast.",biblicalSignificance:"Caesarea features prominently in Acts, including the ministries of Peter and Paul and the Roman administration of Judea.",historicalSignificance:"Herod's harbour transformed the site into a major Mediterranean city and Roman political centre.",archaeology:"The harbour, theatre, palace, inscriptions and urban remains provide extensive evidence for Herodian and Roman Caesarea.",bibleReferences:["Acts 10","Acts 12","Acts 18","Acts 25"],people:["herod","paul","peter","pontius-pilate"],storySlugs:["caesarea-maritima","paul-missions"],themes:["Herod","Rome","Acts","Mediterranean"]},
  {slug:"qumran",name:"Qumran",type:"Settlement / Archaeological site",region:"Dead Sea",era:"Second Temple period",coordinates:{lat:31.7419,lon:35.4593},summary:"A Dead Sea settlement near the caves where the Dead Sea Scrolls were discovered.",biblicalSignificance:"Qumran is not itself a major biblical narrative location, but it is central to the textual and religious context of late Second Temple Judaism.",historicalSignificance:"The site and nearby caves illuminate Jewish communities, manuscript culture and religious diversity before 70 CE.",archaeology:"The settlement and nearby caves produced manuscripts, ritual installations and material culture studied alongside the Dead Sea Scrolls.",bibleReferences:["Context for Second Temple Judaism"],people:["josephus"],storySlugs:["dead-sea-scrolls-context","qumran"],themes:["Dead Sea Scrolls","Judaism","Second Temple"]},
  {slug:"masada",name:"Masada",type:"Fortress / Archaeological site",region:"Judean Desert",era:"Herodian to Roman period",coordinates:{lat:31.3156,lon:35.3536},summary:"Herod's desert fortress and later the site of a famous episode in the First Jewish Revolt.",biblicalSignificance:"Masada is a post-biblical historical site rather than a major biblical narrative setting.",historicalSignificance:"Its remains illuminate Herodian architecture and the Roman siege during the revolt of 66–73/74 CE.",archaeology:"The fortress, siege works, camps and installations preserve unusually visible evidence for Roman siege warfare.",bibleReferences:["Historical context after the New Testament"],people:["herod","titus","josephus"],storySlugs:["masada","jewish-war"],themes:["Herod","Roman siege","Jewish Revolt"]},
  {slug:"babylon",name:"Babylon",type:"Imperial capital / Archaeological site",region:"Mesopotamia",era:"Bronze Age to Hellenistic period",coordinates:{lat:32.542,lon:44.421},summary:"The great Mesopotamian city that became the capital of the Neo-Babylonian Empire.",biblicalSignificance:"Babylon is the setting of Judah's exile and a recurring symbol of imperial power in biblical literature.",historicalSignificance:"Neo-Babylonian Babylon was a major political, religious and architectural centre under Nebuchadnezzar II.",archaeology:"The Ishtar Gate, processional way, temple precincts and monumental remains document the scale of the city, though reconstruction and preservation issues must be considered.",bibleReferences:["2 Kings 24–25","Daniel 1","Jeremiah 29"],people:["daniel","cyrus"],storySlugs:["cyrus-babylon","daniel-babylon","exile"],themes:["Babylon","Exile","Empire"]},
  {slug:"nineveh",name:"Nineveh",type:"Imperial capital / Archaeological site",region:"Upper Mesopotamia",era:"Assyrian Empire",coordinates:{lat:36.36,lon:43.152},summary:"Capital of the Neo-Assyrian Empire and one of the most important archaeological sites for Assyrian history.",biblicalSignificance:"Nineveh appears in Jonah and belongs to the wider Assyrian context of the northern kingdom's destruction.",historicalSignificance:"The city's palaces, libraries and inscriptions preserve extensive evidence for Assyrian imperial administration and warfare.",archaeology:"Excavated palaces, the Library of Ashurbanipal and monumental reliefs provide unusually rich primary evidence.",bibleReferences:["Jonah 1–4","Nahum 1–3","2 Kings 19"],people:["sennacherib"],storySlugs:["nineveh-site","sennacherib"],themes:["Assyria","Imperial capitals","Archaeology"]},
  {slug:"ur",name:"Ur",type:"City / Archaeological site",region:"Southern Mesopotamia",era:"Third millennium BCE onward",coordinates:{lat:30.9626,lon:46.1031},summary:"A major Sumerian city associated with the wider ancient Near Eastern world of the patriarchal traditions.",biblicalSignificance:"Genesis identifies Ur of the Chaldeans as Abraham's place of origin in the biblical narrative.",historicalSignificance:"Ur was a major urban, economic and religious centre long before the biblical patriarchal period.",archaeology:"Excavations exposed royal tombs, temples, domestic quarters and administrative evidence, especially from the Early Dynastic and Ur III periods.",bibleReferences:["Genesis 11:28","Genesis 15:7"],people:["abraham"],storySlugs:["abraham","ur-site"],themes:["Mesopotamia","Abraham","Urbanism"]},
  {slug:"haran",name:"Haran",type:"City / Caravan centre",region:"Upper Mesopotamia",era:"Bronze Age to Iron Age",coordinates:{lat:36.8667,lon:39.0333},summary:"A northern Mesopotamian centre associated with Abraham's migration narrative and later regional kingdoms.",biblicalSignificance:"Genesis describes Haran as a stopping point in Abraham's migration before entry into Canaan.",historicalSignificance:"Haran's location made it important in long-distance trade and the movement of peoples across northern Mesopotamia.",archaeology:"The site contains remains from long occupation, though the relationship between archaeological phases and patriarchal narratives remains uncertain.",bibleReferences:["Genesis 11–12","Genesis 24"],people:["abraham"],storySlugs:["abraham"],themes:["Migration","Mesopotamia","Patriarchs"]},
  {slug:"egypt",name:"Egypt & the Nile",type:"Kingdom / Region",region:"Northeast Africa",era:"Bronze Age to Roman period",coordinates:{lat:30.0444,lon:31.2357},summary:"A major ancient civilization repeatedly connected with Israel's biblical traditions, from the patriarchal narratives to Roman Judea.",biblicalSignificance:"Egypt is central to Joseph, Exodus, prophetic diplomacy and the later flight narrative in Matthew.",historicalSignificance:"Egyptian chronology provides an important external framework for evaluating proposed Exodus dates and Levantine-Egyptian interaction.",archaeology:"Temples, administrative records, inscriptions and settlement archaeology provide extensive evidence for Egyptian power and society.",bibleReferences:["Genesis 12","Genesis 41","Exodus 1–14","Matthew 2"],people:["joseph","moses","aaron","jesus"],storySlugs:["joseph","exodus","egypt-and-the-nile"],themes:["Egypt","Exodus","Migration"]},
  {slug:"sinai",name:"Sinai Wilderness",type:"Region / Wilderness",region:"Sinai Peninsula",era:"Bronze Age to Roman period",coordinates:{lat:29.5,lon:33.9},summary:"The wilderness region associated with Israel's journey, covenant and sanctuary traditions after the Exodus.",biblicalSignificance:"Sinai is the setting of the covenant, lawgiving and major wilderness episodes in Exodus–Numbers.",historicalSignificance:"The precise route and location of biblical Mount Sinai remain debated, and proposed identifications should not be treated as settled archaeological fact.",archaeology:"Archaeology provides broader evidence for ancient travel, mining, settlement and Egyptian-Levantine interaction, but does not establish a single Exodus route.",bibleReferences:["Exodus 19–20","Numbers 1–10","Deuteronomy 5"],people:["moses","aaron"],storySlugs:["exodus","sinai-wilderness"],themes:["Exodus","Covenant","Wilderness"]},
  {slug:"babylonian-jerusalem-route",name:"Babylonian–Jerusalem corridor",type:"Historical corridor",region:"Levant–Mesopotamia",era:"6th century BCE",coordinates:{lat:32.5,lon:40},summary:"The broad route linking Judah with the Babylonian imperial heartland during the deportations and exile.",biblicalSignificance:"The route represents the historical setting of the deportations of Judah and the movement of exiles to Babylon.",historicalSignificance:"Imperial deportation and administrative integration were characteristic features of Neo-Babylonian and later Near Eastern empires.",archaeology:"Evidence is distributed across cities and administrative centres rather than concentrated in a single archaeological site.",bibleReferences:["2 Kings 24–25","Jeremiah 29","Ezekiel 1"],people:["zedekiah","jeremiah","ezekiel","daniel"],storySlugs:["first-deportation","exile"],themes:["Exile","Deportation","Empire"]},
  {slug:"antioch",name:"Antioch",type:"City",region:"Northern Syria",era:"Hellenistic to Roman period",coordinates:{lat:36.2021,lon:36.1606},summary:"A major Hellenistic and Roman city associated with early Christianity and the expansion of the Jesus movement.",biblicalSignificance:"Acts presents Antioch as a major centre of the early Christian movement and Paul's missionary activity.",historicalSignificance:"The city linked Mediterranean, Syrian and Mesopotamian networks and became one of the Roman world's great urban centres.",archaeology:"Although ancient Antioch is partly buried beneath modern Antakya, excavations and mosaics provide evidence for its monumental and domestic life.",bibleReferences:["Acts 11","Acts 13","Galatians 2"],people:["paul","peter"],storySlugs:["paul-missions"],themes:["Early Christianity","Hellenistic cities","Paul"]},
  {slug:"damascus",name:"Damascus",type:"City",region:"Aram / Syria",era:"Bronze Age to Roman period",coordinates:{lat:33.5138,lon:36.2765},summary:"One of the ancient Near East's enduring cities and a major setting in Aramaean, Israelite and early Christian history.",biblicalSignificance:"Damascus appears throughout the Hebrew Bible and becomes central to Paul's conversion narrative in Acts.",historicalSignificance:"Its strategic position made it a major centre for Aram-Damascus and later imperial powers.",archaeology:"The modern city overlays ancient occupation, making direct excavation difficult, but inscriptions and regional archaeology illuminate its history.",bibleReferences:["1 Kings 11","2 Kings 8","Acts 9"],people:["paul","elijah"],storySlugs:["paul"],themes:["Aram","Paul","Trade routes"]},
  {slug:"rome",name:"Rome",type:"Imperial capital",region:"Central Italy",era:"Roman period",coordinates:{lat:41.9028,lon:12.4964},summary:"Capital of the Roman Empire and a major destination in the later history of Paul and the early Christian movement.",biblicalSignificance:"Acts ends with Paul in Rome, and the New Testament's Roman context is essential for understanding first-century Christianity.",historicalSignificance:"Rome was the administrative, military and ideological centre of the Mediterranean empire.",archaeology:"Monumental architecture, inscriptions, roads, cemeteries and literary sources provide extensive evidence for Roman society.",bibleReferences:["Acts 28","Romans 1"],people:["paul","peter"],storySlugs:["paul-missions","book-acts-book"],themes:["Rome","Empire","Early Christianity"]},
  {slug:"antioch-pisidia",name:"Pisidian Antioch",type:"City / Roman colony",region:"Central Anatolia",era:"Hellenistic to Roman period",coordinates:{lat:38.3,lon:31.18},summary:"An Anatolian city associated with Paul's missionary activity in Acts.",biblicalSignificance:"Acts describes preaching and conflict at Pisidian Antioch during Paul's missionary journeys.",historicalSignificance:"The city demonstrates the network of Roman roads and urban centres through which early Christian missionaries travelled.",archaeology:"Monumental remains and inscriptions document the Roman colonial city and its civic institutions.",bibleReferences:["Acts 13"],people:["paul"],storySlugs:["paul-missions"],themes:["Paul","Missionary journeys","Roman roads"]},
  {slug:"corinth",name:"Corinth",type:"City",region:"Greece",era:"Classical to Roman period",coordinates:{lat:37.9064,lon:22.878},summary:"A major Greek and Roman commercial city and one of Paul's most important missionary centres.",biblicalSignificance:"Acts and Paul's letters preserve extensive evidence for the early Christian community at Corinth.",historicalSignificance:"Corinth's position between mainland Greece and the Peloponnese made it economically and strategically important.",archaeology:"The Roman forum, temples, inscriptions and domestic remains illuminate the urban environment behind Paul's letters.",bibleReferences:["Acts 18","1 Corinthians","2 Corinthians"],people:["paul"],storySlugs:["paul-missions"],themes:["Paul","Roman cities","Early Christianity"]},
  {slug:"athens",name:"Athens",type:"City",region:"Greece",era:"Classical to Roman period",coordinates:{lat:37.9838,lon:23.7275},summary:"The famous Greek city where Acts places Paul's speech at the Areopagus.",biblicalSignificance:"Acts 17 depicts Paul engaging the intellectual and religious culture of Athens.",historicalSignificance:"Athens remained an important intellectual and cultural centre under Roman rule despite its political subordination.",archaeology:"The Acropolis, Agora and inscriptions provide extensive evidence for the city's religious and civic environment.",bibleReferences:["Acts 17"],people:["paul"],storySlugs:["paul-missions"],themes:["Paul","Greek world","Philosophy"]},
  {slug:"alexandria",name:"Alexandria",type:"City",region:"Egypt",era:"Hellenistic to Roman period",coordinates:{lat:31.2001,lon:29.9187},summary:"A major Hellenistic city and intellectual centre of the eastern Mediterranean.",biblicalSignificance:"Alexandria is important for the wider Jewish and Christian intellectual world, including the Greek-speaking Jewish diaspora.",historicalSignificance:"Founded by Alexander and developed under the Ptolemies, Alexandria became a major centre of scholarship, trade and multicultural life.",archaeology:"Much of ancient Alexandria lies beneath the modern city and harbour, but underwater archaeology and excavations reveal its monumental landscape.",bibleReferences:["Hellenistic and early Christian context"],people:["alexander"],storySlugs:["alexander","ptolemies"],themes:["Hellenism","Diaspora","Scholarship"]},
];

export const placeMap = Object.fromEntries(places.map(place => [place.slug, place]));
