import Link from "next/link";
import Header from "../../../components/layout/Header";
import { bibleBooks } from "../../../content/bible/books";
import { canonComparison } from "../../../content/bible/canons";
import { deepBookMap } from "../../../content/bible/deep";
import { extendedBookMap, extendedScriptureBooks } from "../../../content/extended/books";
import { getChapterMeta } from "../../../content/bible/chapters";
import { storyMap } from "../../../content/stories";

export function generateStaticParams() {
  return [...bibleBooks.map(book => ({ slug: book.slug })), ...extendedScriptureBooks.map(book => ({ slug: book.slug }))];
}

export default async function UnifiedBookPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const book = bibleBooks.find(item => item.slug === slug);
  const extended = extendedBookMap[slug];
  if (!book && !extended) return <div className="shell"><Header/><main className="mx-auto max-w-3xl px-6 py-24"><h1 className="text-4xl font-semibold">Book not found</h1><Link className="sans mt-6 inline-block text-sm font-bold text-[var(--accent)]" href="/books">← Return to the library</Link></main></div>;

  if (extended) {
    return <div className="shell"><Header/><main className="mx-auto max-w-[1200px] px-4 py-10 sm:px-6 sm:py-14">
      <Link href="/books" className="sans text-sm font-bold text-[var(--accent)]">← All books</Link>
      <header className="mt-7 max-w-5xl"><div className="flex flex-wrap gap-2">{extended.tradition.map(t=><span key={t} className="sans rounded-full border border-[var(--border)] px-3 py-1 text-xs font-bold">{t}</span>)}</div><p className="sans mt-5 text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">{extended.family}</p><h1 className="mt-2 text-5xl font-semibold leading-tight">{extended.name}</h1><p className="mt-5 max-w-4xl text-lg leading-8 text-[var(--muted)]">{extended.summary}</p></header>
      <section className="mt-10 grid gap-4 md:grid-cols-3"><div className="panel rounded-3xl p-5"><p className="sans text-xs font-bold uppercase tracking-[.14em] text-[var(--muted)]">Structure</p><p className="mt-2 font-semibold">{extended.approximateStructure ?? "Varies by edition"}</p></div><div className="panel rounded-3xl p-5"><p className="sans text-xs font-bold uppercase tracking-[.14em] text-[var(--muted)]">Historical period</p><p className="mt-2 font-semibold">{extended.historicalPeriod}</p></div><div className="panel rounded-3xl p-5"><p className="sans text-xs font-bold uppercase tracking-[.14em] text-[var(--muted)]">Tradition</p><p className="mt-2 font-semibold">{extended.tradition.join(" · ")}</p></div></section>
      <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="panel rounded-3xl p-6"><h2 className="text-2xl font-semibold">Historical & literary lens</h2><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{extended.historicalLens}</p></article><article className="panel rounded-3xl p-6"><h2 className="text-2xl font-semibold">Important notes</h2><ul className="mt-4 space-y-3 text-sm leading-7 text-[var(--muted)]">{extended.notes.map(note=><li key={note}>• {note}</li>)}</ul></article></section>
      <section className="mt-8 rounded-3xl bg-[var(--surface-2)] p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Continue exploring</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">This work connects to the wider canon and historical encyclopedia. Use the canon explorer for tradition comparisons and the extended library for related texts.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/canon" className="rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-bold">Compare canons</Link><Link href="/extended" className="rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-bold">Extended library</Link><Link href="/connections" className="rounded-xl border border-[var(--border)] px-4 py-2 text-sm font-bold">Connections</Link></div></section>
    </main></div>;
  }

  // The extended-book branch above can return, so from here onward this is a core Bible book.
  // Keep the explicit guard so TypeScript/Vercel can narrow `book` reliably in production.
  if (!book) return null;

  const guide = deepBookMap[slug];
  const status = canonComparison.find(row => row.slug === slug || row.name === book.name);
  const story = book.guideSlug ? storyMap[book.guideSlug] : undefined;
  const sectionMeta = book.section;

  return <div className="shell"><Header/><main className="mx-auto max-w-[1250px] px-4 py-10 sm:px-6 sm:py-14">
    <div className="sans flex flex-wrap items-center gap-2 text-xs font-bold text-[var(--muted)]"><Link href="/books">Books</Link><span>/</span><span className="text-[var(--accent)]">{book.name}</span></div>
    <header className="mt-8 max-w-5xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">{book.testament} · {sectionMeta}</p><h1 className="mt-3 text-5xl font-semibold leading-tight sm:text-6xl">{guide?.name ?? `The Book of ${book.name}`}</h1><p className="mt-4 text-xl leading-8 text-[var(--muted)]">{guide?.subtitle ?? (story && "summary" in story ? story.summary : undefined) ?? `Explore all ${book.chapters} chapters, the book's place in Scripture, and the historical material connected to it.`}</p></header>

    {guide ? <>
      <section className="mt-9 panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Deep book guide</p><p className="mt-4 text-lg leading-8 text-[var(--muted)]">{guide.overview}</p><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><p className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Genre</p><p className="mt-1 text-sm leading-6">{guide.genre}</p></div><div><p className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Setting</p><p className="mt-1 text-sm leading-6">{guide.setting}</p></div><div><p className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Authorship</p><p className="mt-1 text-sm leading-6">{guide.authorship}</p></div><div><p className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Dating</p><p className="mt-1 text-sm leading-6">{guide.dating}</p></div></div></section>
      <section className="mt-7 grid gap-4 lg:grid-cols-3">{guide.structure.map(s=><div key={s.title} className="panel rounded-2xl p-5"><h2 className="font-semibold">{s.title}</h2><p className="sans mt-1 text-xs font-bold text-[var(--accent)]">Ch. {s.chapters}</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{s.description}</p></div>)}</section>
    </> : story ? <section className="mt-9 panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Existing encyclopedia guide</p><p className="mt-4 text-base leading-8 text-[var(--muted)]">This book already has a historical/literary entry in the encyclopedia. The chapter library below provides the full chapter navigation while the linked guide contains the broader narrative treatment.</p><Link href={`/story/${book.guideSlug}`} className="mt-5 inline-flex rounded-xl bg-[var(--accent)] px-4 py-3 sans text-sm font-bold text-white">Open the existing guide →</Link></section> : null}

    {guide ? <section className="mt-8 grid gap-6 lg:grid-cols-3"><div className="panel rounded-3xl p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">People</p><div className="mt-4 flex flex-wrap gap-2">{guide.majorPeople.map(x=><span key={x} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div><div className="panel rounded-3xl p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Places</p><div className="mt-4 flex flex-wrap gap-2">{guide.majorPlaces.map(x=><span key={x} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div><div className="panel rounded-3xl p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Themes</p><div className="mt-4 flex flex-wrap gap-2">{guide.majorThemes.map(x=><span key={x} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{x}</span>)}</div></div></section> : null}

    <section className="mt-8 panel rounded-3xl p-6 sm:p-9"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Chapter library</p><h2 className="mt-2 text-3xl font-semibold">All {book.chapters} chapters</h2></div><Link href={`/bible?book=${book.slug}`} className="sans text-sm font-bold text-[var(--accent)]">Open chapter grid →</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Array.from({length:book.chapters},(_,i)=>i+1).map(n=>{const deepCh=guide?.chapters.find(x=>x.number===n); const meta=getChapterMeta(book.slug,n,book.name); return <Link key={n} href={`/bible/${book.slug}/${n}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4 transition hover:border-[var(--accent)]"><div className="flex items-center justify-between gap-2"><span className="sans text-xs font-black uppercase tracking-wider text-[var(--accent)]">Chapter {n}</span>{deepCh ? <span className="sans text-[9px] font-black uppercase text-[var(--accent)]">Deep</span> : null}</div><h3 className="mt-2 font-semibold">{deepCh?.title ?? meta.title ?? `Chapter ${n}`}</h3><p className="mt-1 line-clamp-3 text-sm leading-6 text-[var(--muted)]">{deepCh?.summary ?? meta.summary ?? "Open the chapter study page."}</p></Link>})}</div></section>

    <section className="mt-8 grid gap-6 lg:grid-cols-2"><article className="panel rounded-3xl p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Canon & tradition</p>{status ? <><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{status.note}</p><div className="mt-5 grid grid-cols-2 gap-2">{[["Protestant",status.protestant],["Catholic",status.catholic],["Eastern Orthodox",status.easternOrthodox],["Ethiopian Orthodox",status.ethiopianOrthodox]].map(([k,v])=><div key={k} className="rounded-xl bg-[var(--surface-2)] p-3"><p className="sans text-[9px] font-black uppercase tracking-wider text-[var(--accent)]">{k}</p><p className="mt-1 text-xs font-semibold">{String(v).replaceAll("-"," ")}</p></div>)}</div></> : <p className="mt-3 text-sm leading-7 text-[var(--muted)]">Canonical and tradition-specific metadata will continue to expand as the multi-canon library is populated.</p>}</article><article className="panel rounded-3xl p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Continue exploring</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link href="/timeline" className="rounded-xl bg-[var(--surface-2)] p-4 text-sm font-semibold">Timeline →</Link><Link href="/people" className="rounded-xl bg-[var(--surface-2)] p-4 text-sm font-semibold">People →</Link><Link href="/places" className="rounded-xl bg-[var(--surface-2)] p-4 text-sm font-semibold">Atlas →</Link><Link href="/evidence" className="rounded-xl bg-[var(--surface-2)] p-4 text-sm font-semibold">Evidence →</Link></div></article></section>
  </main></div>;
}
