import { Creation } from "./creation";
import { AdamAndEve } from "./adam-and-eve";
import { TheFall } from "./the-fall";
import { CainAndAbel } from "./cain-and-abel";
import { Noah } from "./noah";
import { TheFlood } from "./the-flood";
import { TowerOfBabel } from "./tower-of-babel";
import { Abraham } from "./abraham";
import { Isaac } from "./isaac";
import { Jacob } from "./jacob";
import { Joseph } from "./joseph";
import { Moses } from "./moses";
import { Exodus } from "./exodus";
import { CrossingTheJordan } from "./crossing-the-jordan";
import { Jericho } from "./jericho";
import { Ai } from "./ai";
import { Gibeonites } from "./gibeonites";
import { Deborah } from "./deborah";
import { Gideon } from "./gideon";
import { Samson } from "./samson";
import { Ruth } from "./ruth";
import { Samuel } from "./samuel";
import { Saul } from "./saul";
import { DavidAndGoliath } from "./david-and-goliath";
import { DavidCapturesJerusalem } from "./david-captures-jerusalem";
import { Solomon } from "./solomon";
import { SolomonBuildsTemple } from "./solomon-builds-temple";

import { Rehoboam } from "./rehoboam";
import { Jeroboam } from "./jeroboam";
import { Omri } from "./omri";
import { AhabJezebel } from "./ahab-jezebel";
import { Elijah } from "./elijah";
import { Elisha } from "./elisha";
import { Jehu } from "./jehu";
import { Mesha } from "./mesha";
import { AssyriaWest } from "./assyria-west";
import { TiglatPileser } from "./tiglat-pileser";
import { FallSamaria } from "./fall-samaria";
import { Hezekiah } from "./hezekiah";
import { Sennacherib } from "./sennacherib";
import { Lachish } from "./lachish";
import { Isaiah } from "./isaiah";
import { Manasseh } from "./manasseh";
import { Josiah } from "./josiah";
import { Nineveh } from "./nineveh";
import { Jehoiakim } from "./jehoiakim";
import { FirstDeportation } from "./first-deportation";
import { Zedekiah } from "./zedekiah";
import { Jerusalem586 } from "./jerusalem-586";
import { Exile } from "./exile";
import { DanielBabylon } from "./daniel-babylon";
import { Belshazzar } from "./belshazzar";
import { CyrusBabylon } from "./cyrus-babylon";
import { Zerubbabel } from "./zerubbabel";
import { Ezra } from "./ezra";
import { Nehemiah } from "./nehemiah";
import { Esther } from "./esther";
import { Alexander } from "./alexander";
import { Ptolemies } from "./ptolemies";
import { Antiochus } from "./antiochus";
import { Mattathias } from "./mattathias";
import { JudasMaccabaeus } from "./judas-maccabaeus";
import { Hasmoneans } from "./hasmoneans";
import Pompey from "./pompey";
import { Herod } from "./herod";
import JohnBaptist from "./john-baptist";
import { Jesus } from "./jesus";
import { Pilate } from "./pilate";
import { Paul } from "./paul";
import { James } from "./james";
import { JewishWar } from "./jewish-war";
import { Jerusalem70 } from "./jerusalem-70";
import Masada from "./masada";
import DariusI from "./darius-i";
import Xerxes from "./xerxes";
import Artaxerxes from "./artaxerxes";
import Yehud from "./yehud";
import Elephantine from "./elephantine";
import SecondTempleCompletion from "./second-temple-completion";
import Diadochi from "./diadochi";
import PtolemaicJudea from "./ptolemaic-judea";
import SeleucidJudea from "./seleucid-judea";
import AntiochusIv from "./antiochus-iv";
import DeadSeaScrolls from "./dead-sea-scrolls";
import HasmoneanExpansion from "./hasmonean-expansion";
import Augustus from "./augustus";
import HerodTemple from "./herod-temple";
import HerodSuccessors from "./herod-successors";
import JesusGalilee from "./jesus-galilee";
import Crucifixion from "./crucifixion";
import ResurrectionEarlyTradition from "./resurrection-early-tradition";
import PaulMissions from "./paul-missions";
import JamesJerusalem from "./james-jerusalem";
import JewishRevolt from "./jewish-revolt";
import BarKokhba from "./bar-kokhba";
import { DiadochiWars } from "./diadochi-wars";
import { PtolemaicAdministration } from "./ptolemaic-administration";
import { SeleucidTransition } from "./seleucid-transition";
import { AntiochusIvCrisis } from "./antiochus-iv-crisis";
import { HanukkahTempleRededication } from "./hanukkah-temple-rededication";
import { HasmoneanState } from "./hasmonean-state";
import { HasmoneanCivilWar } from "./hasmonean-civil-war";
import { SecondTempleSociety } from "./second-temple-society";
import { DeadSeaScrollsContext } from "./dead-sea-scrolls-context";
import { RomanProvinceJudea } from "./roman-province-judea";
import { HerodianBuildingProgram } from "./herodian-building-program";
import { JewishSectsFirstCentury } from "./jewish-sects-first-century";
import { JohnBaptistContext } from "./john-baptist-context";
import { JesusHistoricalContext } from "./jesus-historical-context";
import { PaulRomanWorld } from "./paul-roman-world";
import { JerusalemChurch } from "./jerusalem-church";
import { JewishRevoltCauses } from "./jewish-revolt-causes";
import { Jerusalem70Context } from "./jerusalem-70-context";
import { BarKokhbaContext } from "./bar-kokhba-context";
import { RomanRoads } from "./roman-roads";
import { DiasporaJews } from "./diaspora-jews";
import { SynagogueWorld } from "./synagogue-world";
import { JerusalemTemplePriesthood } from "./jerusalem-temple-priesthood";
import { Sanhedrin } from "./sanhedrin";
import { Josephus } from "./josephus";
import { TacitusJudea } from "./tacitus-judea";
import { BarKokhbaAftermath } from "./bar-kokhba-aftermath";
import { Jeremiah } from "./jeremiah";
import { Ezekiel } from "./ezekiel";
import { Daniel } from "./daniel";
import { HaggaiZechariah } from "./haggai-zechariah";
import { Malachi } from "./malachi";
import { MerneptahStele } from "./merneptah-stele";
import { TelDanStele } from "./tel-dan-stele";
import { BlackObelisk } from "./black-obelisk";
import { MeshaStele } from "./mesha-stele";
import { SennacheribPrism } from "./sennacherib-prism";
import { CyrusCylinder } from "./cyrus-cylinder";

import { Jerusalem } from "./jerusalem";
import { Samaria } from "./samaria";
import { Megiddo } from "./megiddo";
import { Hazor } from "./hazor";
import { LachishCity } from "./lachish-city";
import { JerichoSite } from "./jericho-site";
import { Bethlehem } from "./bethlehem";
import { Nazareth } from "./nazareth";
import { Capernaum } from "./capernaum";
import { Bethsaida } from "./bethsaida";
import { CaesareaMaritima } from "./caesarea-maritima";
import { Qumran } from "./qumran";
import { MasadaSite } from "./masada-site";
import { BabylonSite } from "./babylon-site";
import { NinevehSite } from "./nineveh-site";
import { UrSite } from "./ur-site";
import { EgyptAndTheNile } from "./egypt-and-the-nile";
import { SinaiWilderness } from "./sinai-wilderness";
export const stories=[Jerusalem,Samaria,Megiddo,Hazor,LachishCity,JerichoSite,Bethlehem,Nazareth,Capernaum,Bethsaida,CaesareaMaritima,Qumran,MasadaSite,BabylonSite,NinevehSite,UrSite,EgyptAndTheNile,SinaiWilderness,Jeremiah,Ezekiel,Daniel,HaggaiZechariah,Malachi,MerneptahStele,TelDanStele,BlackObelisk,MeshaStele,SennacheribPrism,CyrusCylinder,Creation,AdamAndEve,TheFall,CainAndAbel,Noah,TheFlood,TowerOfBabel,Abraham,Isaac,Jacob,Joseph,Moses,Exodus,CrossingTheJordan,Jericho,Ai,Gibeonites,Deborah,Gideon,Samson,Ruth,Samuel,Saul,DavidAndGoliath,DavidCapturesJerusalem,Solomon,SolomonBuildsTemple,Rehoboam,Jeroboam,Omri,AhabJezebel,Elijah,Elisha,Jehu,Mesha,AssyriaWest,TiglatPileser,FallSamaria,Hezekiah,Sennacherib,Lachish,Isaiah,Manasseh,Josiah,Nineveh,Jehoiakim,FirstDeportation,Zedekiah,Jerusalem586,Exile,DanielBabylon,Belshazzar,CyrusBabylon,Zerubbabel,Ezra,Nehemiah,Esther,Alexander,Ptolemies,Antiochus,Mattathias,JudasMaccabaeus,Hasmoneans,Pompey,Herod,JohnBaptist,Jesus,Pilate,Paul,James,JewishWar,Jerusalem70,Masada,DariusI,Xerxes,Artaxerxes,Yehud,Elephantine,SecondTempleCompletion,Diadochi,PtolemaicJudea,SeleucidJudea,AntiochusIv,DeadSeaScrolls,HasmoneanExpansion,Augustus,HerodTemple,HerodSuccessors,JesusGalilee,Crucifixion,ResurrectionEarlyTradition,PaulMissions,JamesJerusalem,JewishRevolt,BarKokhba,DiadochiWars,PtolemaicAdministration,SeleucidTransition,AntiochusIvCrisis,HanukkahTempleRededication,HasmoneanState,HasmoneanCivilWar,SecondTempleSociety,DeadSeaScrollsContext,RomanProvinceJudea,HerodianBuildingProgram,JewishSectsFirstCentury,JohnBaptistContext,JesusHistoricalContext,PaulRomanWorld,JerusalemChurch,JewishRevoltCauses,Jerusalem70Context,BarKokhbaContext,RomanRoads,DiasporaJews,SynagogueWorld,JerusalemTemplePriesthood,Sanhedrin,Josephus,TacitusJudea,BarKokhbaAftermath];
export const storyMap=Object.fromEntries(stories.map(s=>[s.slug,s]));
