import { Creation } from "./creation";
import { AdamAndEve } from "./adam-and-eve";
import { TheFall } from "./the-fall";
import { CainAndAbel } from "./cain-and-abel";
import { Noah } from "./noah";
import { TheFlood } from "./the-flood";
import { TowerOfBabel } from "./tower-of-babel";
import { Abraham } from "./abraham";
import { Isaac } from "./isaac";
import { Jacob } from "./jacob";
import { Joseph } from "./joseph";
import { Moses } from "./moses";
import { Exodus } from "./exodus";
import { CrossingTheJordan } from "./crossing-the-jordan";
import { Jericho } from "./jericho";
import { Ai } from "./ai";
import { Gibeonites } from "./gibeonites";
import { Deborah } from "./deborah";
import { Gideon } from "./gideon";
import { Samson } from "./samson";
import { Ruth } from "./ruth";
import { Samuel } from "./samuel";
import { Saul } from "./saul";
import { DavidAndGoliath } from "./david-and-goliath";
import { DavidCapturesJerusalem } from "./david-captures-jerusalem";
import { Solomon } from "./solomon";
import { SolomonBuildsTemple } from "./solomon-builds-temple";

import Rehoboam from "./rehoboam";
import Jeroboam from "./jeroboam";
import Omri from "./omri";
import AhabJezebel from "./ahab-jezebel";
import Elijah from "./elijah";
import Elisha from "./elisha";
import Jehu from "./jehu";
import Mesha from "./mesha";
import AssyriaWest from "./assyria-west";
import TiglatPileser from "./tiglat-pileser";
import FallSamaria from "./fall-samaria";
import Hezekiah from "./hezekiah";
import Sennacherib from "./sennacherib";
import Lachish from "./lachish";
import Isaiah from "./isaiah";
import Manasseh from "./manasseh";
import Josiah from "./josiah";
import Nineveh from "./nineveh";
import Jehoiakim from "./jehoiakim";
import FirstDeportation from "./first-deportation";
import Zedekiah from "./zedekiah";
import Jerusalem586 from "./jerusalem-586";
import Exile from "./exile";
import DanielBabylon from "./daniel-babylon";
import Belshazzar from "./belshazzar";
import CyrusBabylon from "./cyrus-babylon";
import Zerubbabel from "./zerubbabel";
import Ezra from "./ezra";
import Nehemiah from "./nehemiah";
import Esther from "./esther";
import Alexander from "./alexander";
import Ptolemies from "./ptolemies";
import Antiochus from "./antiochus";
import Mattathias from "./mattathias";
import JudasMaccabaeus from "./judas-maccabaeus";
import Hasmoneans from "./hasmoneans";
import Pompey from "./pompey";
import Herod from "./herod";
import JohnBaptist from "./john-baptist";
import Jesus from "./jesus";
import Pilate from "./pilate";
import Paul from "./paul";
import James from "./james";
import JewishWar from "./jewish-war";
import Jerusalem70 from "./jerusalem-70";
import Masada from "./masada";
export const stories=[Creation,AdamAndEve,TheFall,CainAndAbel,Noah,TheFlood,TowerOfBabel,Abraham,Isaac,Jacob,Joseph,Moses,Exodus,CrossingTheJordan,Jericho,Ai,Gibeonites,Deborah,Gideon,Samson,Ruth,Samuel,Saul,DavidAndGoliath,DavidCapturesJerusalem,Solomon,SolomonBuildsTemple,Rehoboam,Jeroboam,Omri,AhabJezebel,Elijah,Elisha,Jehu,Mesha,AssyriaWest,TiglatPileser,FallSamaria,Hezekiah,Sennacherib,Lachish,Isaiah,Manasseh,Josiah,Nineveh,Jehoiakim,FirstDeportation,Zedekiah,Jerusalem586,Exile,DanielBabylon,Belshazzar,CyrusBabylon,Zerubbabel,Ezra,Nehemiah,Esther,Alexander,Ptolemies,Antiochus,Mattathias,JudasMaccabaeus,Hasmoneans,Pompey,Herod,JohnBaptist,Jesus,Pilate,Paul,James,JewishWar,Jerusalem70,Masada];
export const storyMap=Object.fromEntries(stories.map(s=>[s.slug,s]));
