export type EvidenceItem = {
  slug: string;
  name: string;
  type: "Inscription" | "Royal record" | "Chronicle" | "Archaeological site" | "Manuscript" | "Seal / object" | "Relief" | "Architectural evidence";
  date: string;
  place: string;
  region: string;
  summary: string;
  significance: string;
  whatItShows: string[];
  limits: string;
  people: string[];
  places: string[];
  kingdoms: string[];
  bibleReferences: string[];
  storySlugs: string[];
  themes: string[];
  confidence: "Strong external anchor" | "Important contextual evidence" | "Archaeological context";
};

export const evidenceItems: EvidenceItem[] = [
  {slug:"merneptah-stele",name:"Merneptah Stele",type:"Inscription",date:"c. 1208 BCE",place:"Egypt",region:"Egypt / Levant",summary:"An Egyptian victory inscription whose reference to Israel is the earliest widely accepted extra-biblical mention of Israel by name.",significance:"The stele is a major chronological and historical anchor for the presence of a group called Israel in the southern Levant by the late 13th century BCE.",whatItShows:["Egyptian royal ideology and military campaigning in Canaan.","Israel was understood as a people rather than a city-state in the inscription's conventional reading."],limits:"It does not describe Israel's origins, the Exodus, Joshua's campaigns, or the later monarchy. The inscription is a royal victory text and must be read in that genre.",people:["moses"],places:["egypt"],kingdoms:["egypt"],bibleReferences:["Exodus 1–15","Joshua 1–12","Judges"],storySlugs:["merneptah-stele"],themes:["Israel","Egypt","Late Bronze Age","Chronology"],confidence:"Strong external anchor"},
  {slug:"tel-dan-stele",name:"Tel Dan Stele",type:"Inscription",date:"9th century BCE",place:"Tel Dan",region:"Northern Levant",summary:"Fragmentary Aramaic royal inscription associated with Aram-Damascus and famous for the phrase commonly read as 'House of David'.",significance:"It is an important external witness to a Davidic dynastic designation in the 9th century BCE.",whatItShows:["Aramaean royal political language.","The existence of a dynastic name connected with David in a later Iron Age context."],limits:"The inscription is fragmentary and does not establish the details of David's biography, kingdom size or every event in Samuel.",people:["david"],places:["hazor"],kingdoms:["aram-damascus","kingdom-of-judah"],bibleReferences:["2 Samuel 5–7","1 Kings 11–15"],storySlugs:["tel-dan-stele"],themes:["David","Aram","Dynasty","Iron Age"],confidence:"Strong external anchor"},
  {slug:"mesha-stele",name:"Mesha Stele",type:"Inscription",date:"9th century BCE",place:"Dibon / Moab",region:"Transjordan",summary:"A Moabite royal inscription describing King Mesha's victories, building projects and conflict with Israel.",significance:"It provides a rare first-person royal voice from a neighbor of Israel and complements the Biblical account of conflict between Moab and Israel.",whatItShows:["Moabite statecraft and religious language.","Conflict with the Omride kingdom and the political geography east of the Jordan."],limits:"As royal propaganda, it presents Mesha's victories from a Moabite perspective and cannot independently verify every Biblical detail.",people:["omri","ahab"],places:[],kingdoms:["moab","kingdom-of-israel"],bibleReferences:["2 Kings 3"],storySlugs:["mesha-stele","mesha"],themes:["Moab","Omrides","War","Royal inscriptions"],confidence:"Strong external anchor"},
  {slug:"black-obelisk",name:"Black Obelisk of Shalmaneser III",type:"Royal record",date:"c. 825 BCE",place:"Nimrud",region:"Assyria / Levant",summary:"Assyrian monument showing tribute from multiple rulers, including Jehu of the House of Omri.",significance:"The depiction and inscription provide unusually concrete evidence connecting Assyrian imperial records with an Israelite ruler named Jehu.",whatItShows:["Assyrian imperial ideology and tribute relationships.","Jehu's political position within the 9th-century Levant."],limits:"The image is not a neutral portrait and the tribute scene does not by itself reconstruct Jehu's complete reign.",people:["jehu"],places:["samaria","nineveh"],kingdoms:["assyrian-empire","kingdom-of-israel"],bibleReferences:["2 Kings 9–10"],storySlugs:["black-obelisk"],themes:["Assyria","Jehu","Tribute","Imperial art"],confidence:"Strong external anchor"},
  {slug:"kurkh-monolith",name:"Kurkh Monoliths",type:"Royal record",date:"853 BCE",place:"Kurkh",region:"Upper Mesopotamia",summary:"Assyrian inscriptions describing the Battle of Qarqar and a coalition that included Ahab of Israel.",significance:"They anchor Ahab within a wider 9th-century BCE geopolitical system and document an Assyrian military campaign in the Levant.",whatItShows:["Ahab as an Assyrian-era political actor.","Coalition warfare among Levantine states."],limits:"Assyrian royal inscriptions emphasize imperial victory and should not be treated as neutral battle reports.",people:["ahab"],places:[],kingdoms:["assyrian-empire","kingdom-of-israel"],bibleReferences:["1 Kings 16–22"],storySlugs:[],themes:["Ahab","Qarqar","Assyria","War"],confidence:"Strong external anchor"},
  {slug:"sennacherib-prism",name:"Sennacherib's Prism",type:"Royal record",date:"early 7th century BCE",place:"Nineveh",region:"Assyria / Judah",summary:"Assyrian royal account of Sennacherib's 701 BCE campaign, including the siege of Judahite cities and the confinement of Hezekiah in Jerusalem.",significance:"It is one of the most important external sources for the Assyrian campaign against Judah in the reign of Hezekiah.",whatItShows:["Hezekiah as king of Judah.","Assyrian conquest of Judahite territory and the capture of fortified cities.","Imperial presentation of Jerusalem as a besieged but not captured city."],limits:"The inscription is a royal victory account and does not narrate the Biblical theological interpretation of the campaign or explain why Jerusalem was not taken.",people:["sennacherib","hezekiah","isaiah"],places:["jerusalem","lachish","nineveh"],kingdoms:["assyrian-empire","kingdom-of-judah"],bibleReferences:["2 Kings 18–19","Isaiah 36–37","2 Chronicles 32"],storySlugs:["sennacherib-prism","sennacherib"],themes:["Sennacherib","Hezekiah","Assyria","701 BCE"],confidence:"Strong external anchor"},
  {slug:"lachish-reliefs",name:"Lachish Reliefs",type:"Relief",date:"c. 700 BCE",place:"Nineveh",region:"Assyria / Judah",summary:"Monumental Assyrian reliefs depicting the capture of Lachish during Sennacherib's campaign against Judah.",significance:"The reliefs provide visual evidence for Assyrian siege warfare and the importance of Lachish in the 701 BCE campaign.",whatItShows:["Siege machinery, deportation and treatment of captives.","The monumental presentation of Lachish as an Assyrian victory."],limits:"The relief program is imperial propaganda rather than a complete archaeological record of the battle.",people:["sennacherib","hezekiah"],places:["lachish","nineveh"],kingdoms:["assyrian-empire","kingdom-of-judah"],bibleReferences:["2 Kings 18","Isaiah 36"],storySlugs:["lachish-reliefs","lachish-city","lachish"],themes:["Lachish","Siege warfare","Assyria","Art"],confidence:"Strong external anchor"},
  {slug:"siloam-inscription",name:"Siloam Inscription",type:"Inscription",date:"late 8th century BCE",place:"Jerusalem",region:"Judah",summary:"A short Hebrew inscription associated with the construction of Hezekiah's water tunnel and describing the meeting of workers excavating from opposite directions.",significance:"It provides direct epigraphic evidence for engineering activity in Jerusalem during the late Iron Age.",whatItShows:["Ancient Hebrew writing and technical language.","A large-scale water engineering project in Jerusalem."],limits:"The inscription does not name Hezekiah directly and cannot by itself prove every detail of the Biblical account of the tunnel.",people:["hezekiah"],places:["jerusalem"],kingdoms:["kingdom-of-judah"],bibleReferences:["2 Kings 20:20","2 Chronicles 32:30"],storySlugs:["siloam-inscription","hezekiahs-tunnel"],themes:["Hezekiah","Jerusalem","Engineering","Hebrew epigraphy"],confidence:"Strong external anchor"},
  {slug:"ketef-hinnom-scrolls",name:"Ketef Hinnom Silver Scrolls",type:"Seal / object",date:"late 7th–early 6th century BCE",place:"Jerusalem",region:"Judah",summary:"Tiny silver amulets inscribed with Hebrew text containing wording closely related to the Priestly Blessing.",significance:"They are among the earliest known surviving textual witnesses to Biblical passages or closely related liturgical wording.",whatItShows:["Use of written religious formulas in late First Temple Judah.","The antiquity of wording related to Numbers 6:24–26."],limits:"The relationship between the inscriptions and the final literary form of Numbers must be treated carefully; they are not copies of a complete Biblical manuscript.",people:[],places:["jerusalem"],kingdoms:["kingdom-of-judah"],bibleReferences:["Numbers 6:24–26"],storySlugs:["ketef-hinnom"],themes:["Hebrew","Priestly Blessing","First Temple","Manuscripts"],confidence:"Strong external anchor"},
  {slug:"babylonian-chronicles",name:"Babylonian Chronicles",type:"Chronicle",date:"6th century BCE",place:"Babylon",region:"Mesopotamia / Judah",summary:"Cuneiform chronological records that preserve imperial events including Nebuchadnezzar II's campaigns in the Levant.",significance:"They provide an independent chronological framework for major Babylonian military events surrounding the fall of Judah.",whatItShows:["Babylonian campaigns and imperial chronology.","The broader political context in which Jerusalem and Judah were conquered."],limits:"The surviving chronicles are selective and do not provide a full narrative of the destruction of Jerusalem.",people:["zedekiah","jeremiah"],places:["babylon","jerusalem"],kingdoms:["neo-babylonian-empire","kingdom-of-judah"],bibleReferences:["2 Kings 24–25","Jeremiah 52"],storySlugs:["babylonian-chronicles"],themes:["Babylon","Exile","Chronology","Nebuchadnezzar"],confidence:"Strong external anchor"},
  {slug:"nabonidus-cylinder",name:"Nabonidus Cylinder",type:"Royal record",date:"6th century BCE",place:"Babylonian world",region:"Mesopotamia",summary:"Royal inscription associated with Nabonidus, illustrating Babylonian restoration projects and royal ideology.",significance:"It illuminates the final decades of the Neo-Babylonian Empire, the political world immediately before Cyrus's conquest.",whatItShows:["Babylonian royal restoration and temple patronage.","The political and religious world inherited by the Persian Empire."],limits:"It is not a narrative of the Persian conquest and should not be used as a substitute for the Babylonian Chronicle or later Persian evidence.",people:["cyrus"],places:["babylon"],kingdoms:["neo-babylonian-empire","achaemenid-persia"],bibleReferences:["Daniel 5","Isaiah 45"],storySlugs:["nabonidus-cylinder"],themes:["Babylon","Nabonidus","Cyrus","Empire"],confidence:"Important contextual evidence"},
  {slug:"cyrus-cylinder",name:"Cyrus Cylinder",type:"Royal record",date:"6th century BCE",place:"Babylon",region:"Mesopotamia / Persia",summary:"A Babylonian-language inscription celebrating Cyrus's conquest of Babylon and restoration of temples and cult images.",significance:"It is an important primary source for Cyrus's imperial ideology and Babylonian political transition.",whatItShows:["Cyrus presenting himself within Babylonian royal traditions.","Imperial policies of restoration and temple patronage in the Babylonian setting."],limits:"It is not a universal declaration of modern human rights and should not be read as a direct transcript of the Biblical decree permitting Judean return.",people:["cyrus"],places:["babylon"],kingdoms:["achaemenid-persia","neo-babylonian-empire"],bibleReferences:["Ezra 1","2 Chronicles 36:22–23"],storySlugs:["cyrus-cylinder"],themes:["Cyrus","Persia","Return","Imperial ideology"],confidence:"Strong external anchor"},
  {slug:"dead-sea-scrolls",name:"Dead Sea Scrolls",type:"Manuscript",date:"3rd century BCE–1st century CE",place:"Qumran / Judean Desert",region:"Judea",summary:"A large collection of ancient Jewish manuscripts preserving biblical texts, sectarian works, legal material and other writings.",significance:"The scrolls transformed the study of the textual history and diversity of Second Temple Judaism.",whatItShows:["Multiple textual traditions of Biblical books before the medieval Masoretic manuscripts.","The diversity of Jewish interpretation, law and community life in the late Second Temple period."],limits:"The scrolls do not represent the beliefs of all Jews and should not be treated as a single community's complete library without qualification.",people:["jesus","josephus"],places:["qumran"],kingdoms:["hasmonean-state","roman-empire"],bibleReferences:["Isaiah 40–66","Psalms","Deuteronomy"],storySlugs:["dead-sea-scrolls","dead-sea-scrolls-context","qumran"],themes:["Second Temple","Textual history","Judaism","Manuscripts"],confidence:"Strong external anchor"},
  {slug:"pilate-stone",name:"Pilate Stone",type:"Inscription",date:"c. 26–36 CE",place:"Caesarea Maritima",region:"Roman Judea",summary:"A Latin inscription naming Pontius Pilate and identifying him as prefect of Judaea.",significance:"It is direct archaeological evidence for Pontius Pilate's office and Roman administration in Judaea.",whatItShows:["Pilate's official title and role under the Roman administration.","Latin epigraphic practice in provincial Judaea."],limits:"The inscription does not independently establish the details of Jesus's trial or crucifixion narrative.",people:["pontius-pilate","jesus"],places:["caesarea-maritima"],kingdoms:["roman-empire","herodian-kingdom"],bibleReferences:["Matthew 27","Mark 15","Luke 23","John 18–19"],storySlugs:["pilate-stone","pilate"],themes:["Pilate","Roman Judea","Jesus","Epigraphy"],confidence:"Strong external anchor"},
  {slug:"herod-temple-archaeology",name:"Herodian Temple and Jerusalem Archaeology",type:"Architectural evidence",date:"late 1st century BCE–1st century CE",place:"Jerusalem",region:"Roman Judea",summary:"Architectural remains and associated material evidence illuminate the monumental rebuilding of Jerusalem under Herod the Great and his successors.",significance:"The archaeology provides the physical setting for the Jerusalem Temple complex encountered in the Gospels and early Christianity.",whatItShows:["Monumental engineering and urban transformation under Herodian rule.","The scale and complexity of the Temple Mount and surrounding city."],limits:"Much of the Temple itself was destroyed in 70 CE, so reconstruction depends on surviving structures, later remains and comparative evidence.",people:["herod","jesus","james"],places:["jerusalem"],kingdoms:["herodian-kingdom","roman-empire"],bibleReferences:["Matthew 24","Mark 13","John 2"],storySlugs:["herod-temple","second-temple-society"],themes:["Herod","Temple","Jerusalem","Roman Judea"],confidence:"Archaeological context"},
  {slug:"hezekiahs-tunnel",name:"Hezekiah's Tunnel",type:"Architectural evidence",date:"late 8th century BCE",place:"Jerusalem",region:"Judah",summary:"A water tunnel carrying the Gihon spring's water toward the Siloam area, associated with Jerusalem's late Iron Age fortification and water management.",significance:"The tunnel is one of the clearest surviving examples of large-scale water engineering in Iron Age Jerusalem.",whatItShows:["Urban water management under conditions of military threat.","Ancient engineering and the adaptation of Jerusalem's topography."],limits:"Dating details and the precise sequence of construction remain subjects of archaeological discussion; association with Hezekiah is strong but should be presented with appropriate nuance.",people:["hezekiah"],places:["jerusalem"],kingdoms:["kingdom-of-judah"],bibleReferences:["2 Kings 20:20","2 Chronicles 32:30"],storySlugs:["hezekiahs-tunnel","hezekiah"],themes:["Engineering","Water systems","Hezekiah","Jerusalem"],confidence:"Archaeological context"},
  {slug:"lachish-city",name:"Lachish Archaeological Remains",type:"Archaeological site",date:"Bronze Age–Hellenistic period",place:"Lachish",region:"Southern Levant",summary:"A major fortified tell whose destruction layers and architecture illuminate the history of Judah and its regional neighbors.",significance:"Lachish is especially important for understanding the Assyrian campaign of 701 BCE and the military landscape of Judah.",whatItShows:["Fortifications, gates and administrative structures.","Material evidence for destruction and rebuilding across multiple periods."],limits:"Archaeology provides physical evidence for destruction and occupation but cannot automatically identify every historical event represented by a layer.",people:["hezekiah","sennacherib"],places:["lachish"],kingdoms:["kingdom-of-judah","assyrian-empire"],bibleReferences:["2 Kings 18","2 Chronicles 32"],storySlugs:["lachish-city","lachish"],themes:["Archaeology","Judah","Assyria","Fortifications"],confidence:"Archaeological context"},
  {slug:"hazor-destruction",name:"Hazor and its Destruction Layers",type:"Archaeological site",date:"Bronze Age–Iron Age",place:"Hazor",region:"Northern Levant",summary:"One of the largest archaeological sites in the southern Levant, important for studying Canaanite urbanism, Israelite settlement and regional destruction horizons.",significance:"Hazor is central to debates about the chronology and causes of destruction and political transition in the Late Bronze and early Iron Ages.",whatItShows:["Large Canaanite urban architecture and trade connections.","Destruction and rebuilding sequences that are essential for chronological debate."],limits:"Archaeological destruction layers cannot by themselves prove a specific Biblical campaign or date without broader chronological and comparative evidence.",people:["joshua"],places:["hazor"],kingdoms:["kingdom-of-israel"],bibleReferences:["Joshua 11"],storySlugs:["hazor"],themes:["Canaan","Conquest","Archaeology","Chronology"],confidence:"Archaeological context"},
  {slug:"ur-archaeology",name:"Ur and Mesopotamian Urbanism",type:"Archaeological site",date:"3rd–1st millennium BCE",place:"Ur",region:"Southern Mesopotamia",summary:"The excavated city of Ur provides rich evidence for Mesopotamian urban society, temples, administration and long-distance trade.",significance:"Ur is especially relevant to discussions of the cultural world behind the patriarchal narratives, while the archaeological city should not be equated directly with every detail of Genesis.",whatItShows:["Urban institutions, writing, religion and trade in ancient Mesopotamia.","The complexity of southern Mesopotamian society across multiple periods."],limits:"Archaeology at Ur cannot independently verify Abraham's biography or migration route.",people:["abraham"],places:["ur"],kingdoms:[],bibleReferences:["Genesis 11–12"],storySlugs:["ur-site"],themes:["Mesopotamia","Abraham","Urbanism","Trade"],confidence:"Archaeological context"},
  {slug:"nabonidus-chronology",name:"Nabonidus and the Fall of Babylon",type:"Chronicle",date:"6th century BCE",place:"Babylon",region:"Mesopotamia",summary:"The final decades of Babylonian rule are illuminated by chronicles and royal inscriptions surrounding Nabonidus and Cyrus.",significance:"These sources help anchor the transition from Neo-Babylonian to Persian imperial rule.",whatItShows:["Babylonian royal administration and religious politics.","The historical setting for Cyrus's conquest."],limits:"No single surviving text gives a complete, modern-style narrative of the conquest.",people:["cyrus"],places:["babylon"],kingdoms:["neo-babylonian-empire","achaemenid-persia"],bibleReferences:["Daniel 5","Ezra 1"],storySlugs:["nabonidus-cylinder","babylonian-chronicles"],themes:["Babylon","Persia","Chronology"],confidence:"Important contextual evidence"},
  {slug:"roman-roads",name:"Roman Roads and the Pauline World",type:"Architectural evidence",date:"1st century BCE–1st century CE",place:"Eastern Mediterranean",region:"Roman Empire",summary:"Roads, milestones and urban infrastructure created the physical network through which people, goods, armies and ideas moved across the Roman world.",significance:"They provide material context for the missionary journeys and urban geography described in Acts and Paul's letters.",whatItShows:["Connectivity among Roman cities and provinces.","The logistical infrastructure of the imperial world."],limits:"A road network demonstrates mobility possibilities, not the exact itinerary or timing of an individual traveler unless corroborated by textual evidence.",people:["paul"],places:["antioch-pisidia","corinth","athens","rome"],kingdoms:["roman-empire"],bibleReferences:["Acts 13–28","Romans"],storySlugs:["roman-roads","paul-missions"],themes:["Paul","Roman Empire","Mobility","Infrastructure"],confidence:"Archaeological context"},
  {slug:"pilate-administration",name:"Roman Administrative Inscriptions in Judaea",type:"Inscription",date:"1st century CE",place:"Caesarea and Judaea",region:"Roman Judea",summary:"Latin and Greek inscriptions illuminate the institutions, officials and public building culture of Roman provincial administration.",significance:"They help situate the Gospel narratives within a real Roman provincial system of governors, cities and civic institutions.",whatItShows:["Roman titles and administrative practice.","The multilingual public culture of the eastern Mediterranean."],limits:"Administrative inscriptions provide institutional context but rarely address individual Gospel episodes directly.",people:["pontius-pilate","herod"],places:["caesarea-maritima"],kingdoms:["roman-empire","herodian-kingdom"],bibleReferences:["Luke 3","Luke 23","Acts 23–26"],storySlugs:["pilate-stone","roman-province-judea"],themes:["Roman administration","Judea","Epigraphy"],confidence:"Important contextual evidence"},
];

export const evidenceMap = Object.fromEntries(evidenceItems.map(item => [item.slug, item]));
