import Timeline from '../components/Timeline';
import {Compass, Layers3, ScrollText, Search, ShieldQuestion} from 'lucide-react';

export default function Home(){return <div className="paper-grid grain min-h-screen selection">
 <header className="border-b border-[#d8cdbb] bg-[#18212a] text-[#f6efe3]">
  <div className="mx-auto max-w-7xl px-4 py-5"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl border border-white/15 bg-white/5"><Compass size={23}/></div><div><div className="sans text-[10px] font-bold uppercase tracking-[.28em] text-[#d8bd8e]">The Biblical World</div><h1 className="text-lg font-bold sm:text-xl">Historical Master Timeline</h1></div></div><div className="hidden sans text-xs text-[#c9c4bb] sm:block">Bible · Archaeology · Inscriptions · Empires · Classical sources</div></div></div>
 </header>
 <section className="border-b border-[#d8cdbb] bg-[#efe7d7]">
  <div className="mx-auto max-w-7xl px-4 py-14 sm:py-20"><div className="max-w-4xl"><div className="sans text-xs font-bold uppercase tracking-[.24em] text-[#8b5e34]">A living historical atlas</div><h2 className="mt-4 text-5xl font-bold leading-[.98] tracking-tight sm:text-7xl">The Bible in its<br/><span className="text-[#8b5e34]">historical world.</span></h2><p className="mt-6 max-w-3xl text-lg leading-8 text-stone-700 sm:text-xl">A chronological journey from the ancient Near East to the early Christian era, placing biblical narratives beside archaeology, inscriptions, imperial records, ancient historians and material evidence.</p><div className="mt-8 flex flex-wrap gap-3 sans text-sm"><span className="rounded-full border border-[#cbb99d] bg-[#fffaf1] px-4 py-2">Source-critical</span><span className="rounded-full border border-[#cbb99d] bg-[#fffaf1] px-4 py-2">Chronological</span><span className="rounded-full border border-[#cbb99d] bg-[#fffaf1] px-4 py-2">Evidence-tagged</span><span className="rounded-full border border-[#cbb99d] bg-[#fffaf1] px-4 py-2">Built to expand</span></div></div></div>
 </section>
 <section className="border-b border-[#d8cdbb] bg-[#fffdf8]"><div className="mx-auto grid max-w-7xl gap-0 sm:grid-cols-3">{[[Layers3,'8','eras mapped'],[ScrollText,'24','starter events'],[ShieldQuestion,'4','evidence confidence levels']].map(([Icon,n,label]:any)=><div key={label} className="flex items-center gap-4 border-b border-[#e4dbce] px-5 py-5 sm:border-b-0 sm:border-r last:border-r-0"><Icon size={21} className="text-[#8b5e34]"/><div><div className="text-2xl font-bold">{n}</div><div className="sans text-xs uppercase tracking-wider text-stone-500">{label}</div></div></div>)}</div></section>
 <Timeline/>
 <footer className="border-t border-[#d8cdbb] bg-[#18212a] text-[#d7d1c7]"><div className="mx-auto max-w-7xl px-4 py-10"><div className="grid gap-8 md:grid-cols-[1.4fr_1fr_1fr]"><div><div className="sans text-xs font-bold uppercase tracking-[.2em] text-[#d8bd8e]">Research project</div><p className="mt-3 max-w-md text-sm leading-6 text-[#aaa49b]">This first build is intentionally a foundation. V2 adds the pre-Israel world, parallel regional context, expanded source trails, historical cautions and event research panels. Later increments will add geographic maps, dynasty charts, archaeological sites, people profiles and the apostolic/Christianity modules.</p></div><div><h3 className="font-bold text-white">Evidence layers</h3><p className="mt-3 text-sm leading-6 text-[#aaa49b]">Biblical texts are presented alongside independent evidence without assuming that every source answers the same historical question.</p></div><div><h3 className="font-bold text-white">Version</h3><p className="mt-3 font-mono text-sm text-[#aaa49b]">v0.2 · Ancient Near East expansion<br/>Static-first · Next.js<br/>Designed for incremental expansion</p></div></div></div></footer>
 </div>}
