import Link from "next/link";
import Header from "../../../components/layout/Header";
import { people, personMap } from "../../../content/people";
import { storyMap } from "../../../content/stories";

export function generateStaticParams() { return people.map(person => ({ slug: person.slug })); }

export default async function PersonPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const person = personMap[slug];
  if (!person) return <div className="shell"><Header/><main className="mx-auto max-w-3xl px-6 py-24"><h1 className="text-4xl font-semibold">Person not found</h1><Link className="sans mt-6 inline-block text-sm font-bold text-[var(--accent)]" href="/people">Return to People →</Link></main></div>;
  const relatedPeople = (person.relationships ?? []).map(r => ({ ...r, person: personMap[r.person] })).filter(r => r.person);
  const stories = (person.storySlugs ?? []).map(s => storyMap[s]).filter(Boolean);
  return <div className="shell"><Header/><main className="mx-auto max-w-[1180px] px-5 py-10 sm:px-6 sm:py-14">
    <div className="sans flex flex-wrap items-center gap-2 text-xs font-bold text-[var(--muted)]"><Link href="/people" className="hover:text-[var(--text)]">People</Link><span>/</span><span className="text-[var(--accent)]">{person.name}</span></div>
    <div className="mt-5"><Link href={`/connections?focus=person:${person.slug}`} className="sans inline-flex rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-2 text-sm font-bold hover:border-[var(--accent)]">Explore connections →</Link></div>
    <header className="mt-8 max-w-5xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">{person.era} · {person.testament}</p><h1 className="mt-3 text-5xl font-semibold leading-tight sm:text-6xl">{person.name}</h1><p className="sans mt-3 text-lg font-semibold text-[var(--muted)]">{person.epithet ?? person.role}</p><p className="mt-5 max-w-4xl text-xl leading-9 text-[var(--muted)]">{person.summary}</p></header>
    <div className="mt-10 grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px]">
      <article className="space-y-6">
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Historical profile</p><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Role</dt><dd className="mt-1 text-lg">{person.role}</dd></div><div><dt className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Period</dt><dd className="mt-1 text-lg">{person.period}</dd></div><div className="sm:col-span-2"><dt className="sans text-xs font-bold uppercase tracking-wider text-[var(--muted)]">Historical assessment</dt><dd className="mt-2 text-lg leading-8 text-[var(--muted)]">{person.historicalNote}</dd></div></dl></section>
        {relatedPeople.length ? <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Relationships</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{relatedPeople.map(({person: related, relation})=><Link key={related.slug} href={`/people/${related.slug}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4 hover:border-[var(--accent)]"><h2 className="text-lg font-semibold">{related.name}</h2><p className="sans mt-1 text-xs font-bold uppercase tracking-wider text-[var(--accent)]">{relation}</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{related.epithet ?? related.role}</p></Link>)}</div></section> : null}
        <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Biblical references</p><div className="mt-4 flex flex-wrap gap-2">{person.biblicalReferences.map(ref=><span key={ref} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{ref}</span>)}</div></section>
        {stories.length ? <section className="panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Connected encyclopedia entries</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{stories.map((story:any)=><Link key={story.slug} href={`/story/${story.slug}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4 hover:border-[var(--accent)]"><span className="sans text-[10px] font-bold uppercase tracking-wider text-[var(--accent)]">{story.category ?? "Encyclopedia"}</span><h2 className="mt-1 text-lg font-semibold">{story.title}</h2><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{story.summary ?? story.subtitle ?? "Explore the related article."}</p></Link>)}</div></section> : null}
        <section className="panel-muted rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Historical evidence</p><ul className="mt-4 space-y-3">{person.evidence.map(item=><li key={item} className="flex gap-3 text-base leading-7 text-[var(--muted)]"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[var(--accent)]"/>{item}</li>)}</ul></section>
      </article>
      <aside className="space-y-4 lg:sticky lg:top-24 lg:h-fit"><div className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--muted)]">Quick facts</p><div className="mt-4 space-y-4"><div><p className="sans text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Era</p><p className="mt-1 font-semibold">{person.era}</p></div><div><p className="sans text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Period</p><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{person.period}</p></div>{person.places?.length ? <div><p className="sans text-[10px] font-bold uppercase tracking-wider text-[var(--muted)]">Places</p><div className="mt-2 flex flex-wrap gap-2">{person.places.map(place=><span key={place} className="sans rounded-full border border-[var(--border)] px-2.5 py-1 text-xs text-[var(--muted)]">{place}</span>)}</div></div> : null}</div></div><div className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--muted)]">Themes</p><div className="mt-3 flex flex-wrap gap-2">{person.themes.map(theme=><span key={theme} className="sans rounded-full bg-[var(--surface-2)] px-3 py-2 text-xs font-semibold">{theme}</span>)}</div></div><Link href="/timeline" className="panel block rounded-3xl p-5 hover:border-[var(--accent)]"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--muted)]">See the wider context</p><p className="mt-2 font-semibold">Open the historical timeline →</p></Link></aside>
    </div>
  </main></div>;
}
