import Link from "next/link";
import { notFound } from "next/navigation";
import Header from "../../../components/layout/Header";
import { eventMap, events } from "../../../content/events";
import { people } from "../../../content/people";
import { places } from "../../../content/places";
import { kingdoms } from "../../../content/kingdoms";

export function generateStaticParams(){ return events.map(e=>({slug:e.slug})); }

export default async function EventPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params; const event=eventMap[slug]; if(!event) notFound();
  const linkedPeople=event.participants.map(s=>people.find(p=>p.slug===s)).filter(Boolean);
  const linkedPlaces=event.places.map(s=>places.find(p=>p.slug===s)).filter(Boolean);
  const linkedKingdoms=event.kingdoms.map(s=>kingdoms.find(k=>k.slug===s)).filter(Boolean);
  return <div className="shell"><Header/><main className="mx-auto max-w-[1100px] px-5 py-10 sm:px-6 sm:py-14">
    <Link href="/events" className="sans text-sm font-bold text-[var(--accent)]">← All historical events</Link>
    <div className="mt-5"><Link href={`/connections?focus=event:${event.slug}`} className="sans inline-flex rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-2 text-sm font-bold hover:border-[var(--accent)]">Explore connections →</Link></div>
    <header className="mt-8 border-b border-[var(--border)] pb-10"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">{event.type} · {event.confidence}</p><h1 className="mt-3 text-5xl font-semibold sm:text-6xl">{event.name}</h1><p className="mt-4 max-w-4xl text-xl leading-9 text-[var(--muted)]">{event.summary}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="panel-muted rounded-2xl p-4"><p className="sans text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">Date</p><p className="mt-1 font-semibold">{event.date}</p></div><div className="panel-muted rounded-2xl p-4"><p className="sans text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">Era</p><p className="mt-1 font-semibold">{event.era}</p></div><div className="panel-muted rounded-2xl p-4"><p className="sans text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">Location</p><p className="mt-1 font-semibold">{event.location}</p></div></div></header>
    <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><article className="article"><section><h2>Historical significance</h2><p>{event.historicalSignificance}</p></section><section><h2>Biblical context</h2><p>{event.biblicalContext}</p></section><section><h2>Outcome</h2><p>{event.outcome}</p></section><section><h2>Evidence & sources</h2><ul>{event.evidence.map(x=><li key={x}>{x}</li>)}</ul></section><section><h2>Biblical references</h2><div className="flex flex-wrap gap-2">{event.bibleReferences.length?event.bibleReferences.map(r=><span key={r} className="sans rounded-full border border-[var(--border)] px-3 py-1.5 text-xs font-semibold">{r}</span>):<span className="text-sm text-[var(--muted)]">No direct Biblical reference; this is part of the historical context surrounding the Biblical period.</span>}</div></section></article>
      <aside className="space-y-5"><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">People</h2><div className="mt-3 space-y-2">{linkedPeople.length?linkedPeople.map(p=><Link key={p!.slug} href={`/people/${p!.slug}`} className="block rounded-xl border border-[var(--border)] p-3 hover:border-[var(--accent)]"><span className="font-semibold">{p!.name}</span><span className="sans mt-1 block text-xs text-[var(--muted)]">{p!.role}</span></Link>):<p className="text-sm text-[var(--muted)]">No individual figure is directly linked.</p>}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Places</h2><div className="mt-3 space-y-2">{linkedPlaces.map(p=><Link key={p!.slug} href={`/places/${p!.slug}`} className="block rounded-xl border border-[var(--border)] p-3 hover:border-[var(--accent)]"><span className="font-semibold">{p!.name}</span><span className="sans mt-1 block text-xs text-[var(--muted)]">{p!.region}</span></Link>)}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Political context</h2><div className="mt-3 space-y-2">{linkedKingdoms.map(k=><Link key={k!.slug} href={`/kingdoms/${k!.slug}`} className="block rounded-xl border border-[var(--border)] p-3 hover:border-[var(--accent)]"><span className="font-semibold">{k!.name}</span><span className="sans mt-1 block text-xs text-[var(--muted)]">{k!.dates}</span></Link>)}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Related evidence</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Evidence items are cross-linked through the wider encyclopedia and can be reached through the Evidence library.</p><Link href="/evidence" className="mt-4 block font-bold text-[var(--accent)]">Explore evidence →</Link></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Related articles</h2><div className="mt-3 space-y-2">{event.storySlugs.map(s=><Link key={s} href={`/story/${s}`} className="block rounded-xl bg-[var(--surface-2)] p-3 text-sm font-semibold hover:text-[var(--accent)]">Open encyclopedia article →</Link>)}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Themes</h2><div className="mt-3 flex flex-wrap gap-2">{event.themes.map(t=><span key={t} className="sans rounded-full border border-[var(--border)] px-3 py-1.5 text-xs font-semibold">{t}</span>)}</div></section></aside></div>
  </main></div>
}
