export const chapters = [
  { id:"beginnings", title:"Beginnings", description:"Creation, Adam and Eve, the Fall, Cain and Abel, Noah, the Flood and Babel.", stories:["creation","adam-and-eve","the-fall","cain-and-abel","noah","the-flood","tower-of-babel"] },
  { id:"patriarchs", title:"Abraham and the Patriarchs", description:"Abraham, Isaac, Jacob and Joseph.", stories:["abraham","isaac","jacob","joseph"] },
  { id:"exodus", title:"Egypt and Exodus", description:"Israel in Egypt, Moses, Passover, Exodus and Sinai.", stories:["moses","exodus"] },
  { id:"conquest", title:"Canaan and the Judges", description:"Joshua, Jericho, the conquest narratives, Deborah, Gideon, Samson, Ruth and Samuel.", stories:["crossing-the-jordan","jericho","ai","gibeonites","deborah","gideon","samson","ruth","samuel"] },
  { id:"kings", title:"Saul, David and Solomon", description:"The first monarchy, David's rise, Jerusalem and the First Temple.", stories:["saul","david-and-goliath","david-captures-jerusalem","solomon","solomon-builds-temple"] },
  { id:"divided", title:"The Two Kingdoms", description:"Israel and Judah, prophets, Assyria and the fall of Samaria.", stories:["rehoboam","jeroboam","omri","ahab-jezebel","elijah","elisha","jehu","mesha","assyria-west","tiglat-pileser","fall-samaria","hezekiah","sennacherib","lachish","isaiah","manasseh","josiah","nineveh"] },
  { id:"exile", title:"Babylon and the Exile", description:"Josiah, Jerusalem's destruction, exile and the rise of Persia.", stories:["jehoiakim","first-deportation","zedekiah","jerusalem-586","exile","daniel-babylon","belshazzar","cyrus-babylon"] },
  { id:"return", title:"Return and the Second Temple", description:"Cyrus, Zerubbabel, Ezra, Nehemiah and Persian-period Jerusalem.", stories:["zerubbabel","ezra","nehemiah","esther"] },
  { id:"maccabees", title:"Greeks and the Maccabees", description:"Alexander, the Seleucids, Antiochus IV and the Hasmoneans.", stories:["alexander","ptolemies","antiochus","mattathias","judas-maccabaeus","hasmoneans"] },
  { id:"jesus", title:"Rome, Herod and Jesus", description:"The Roman world, Herod, the life and ministry of Jesus.", stories:["pompey","herod","john-baptist","jesus","pilate"] },
  { id:"church", title:"The Early Church", description:"Acts, Paul, Jerusalem, Rome and the first generations of Christianity.", stories:["paul","james","jewish-war","jerusalem-70","masada"] }
];