export const chapters = [
  { id:"beginnings", title:"Beginnings", description:"Creation, Adam and Eve, the Fall, Cain and Abel, Noah, the Flood and Babel.", stories:["creation","adam-and-eve","the-fall","cain-and-abel","noah","the-flood","tower-of-babel"] },
  { id:"patriarchs", title:"Abraham and the Patriarchs", description:"Abraham, Isaac, Jacob and Joseph.", stories:["abraham","isaac","jacob","joseph"] },
  { id:"exodus", title:"Egypt and Exodus", description:"Israel in Egypt, Moses, Passover, Exodus and Sinai.", stories:["moses","exodus"] },
  { id:"conquest", title:"Canaan and the Judges", description:"Joshua, Jericho, the conquest narratives, Deborah, Gideon, Samson, Ruth and Samuel.", stories:["crossing-the-jordan","jericho","ai","gibeonites","deborah","gideon","samson","ruth","samuel"] },
  { id:"kings", title:"Saul, David and Solomon", description:"The first monarchy, David's rise, Jerusalem and the First Temple.", stories:["saul","david-and-goliath","david-captures-jerusalem","solomon","solomon-builds-temple"] },
  { id:"divided", title:"The Two Kingdoms", description:"Israel and Judah, prophets, Assyria and the fall of Samaria.", stories:["rehoboam","jeroboam","omri","ahab-jezebel","elijah","elisha","jehu","mesha","assyria-west","tiglat-pileser","fall-samaria","hezekiah","sennacherib","lachish","isaiah","manasseh","josiah","nineveh"] },
  { id:"exile", title:"Babylon and the Exile", description:"Josiah, Jerusalem's destruction, exile and the rise of Persia.", stories:["jehoiakim","first-deportation","zedekiah","jerusalem-586","exile","daniel-babylon","belshazzar","cyrus-babylon"] },
  { id:"return", title:"Return and the Second Temple", description:"Cyrus, Zerubbabel, Ezra, Nehemiah and Persian-period Jerusalem.", stories:["zerubbabel","ezra","nehemiah","esther"] },
  { id:"maccabees", title:"Greeks and the Maccabees", description:"Alexander, the Seleucids, Antiochus IV and the Hasmoneans.", stories:["alexander","ptolemies","antiochus","mattathias","judas-maccabaeus","hasmoneans"] },
  { id:"jesus", title:"Rome, Herod and Jesus", description:"The Roman world, Herod, the life and ministry of Jesus.", stories:["pompey","herod","john-baptist","jesus","pilate"] },
  { id:"church", title:"The Early Church", description:"Acts, Paul, Jerusalem, Rome and the first generations of Christianity.", stories:["paul","james","jewish-war","jerusalem-70","masada"] }
,
  { id:"persian-depth", title:"Persian Empire and the Restored Community", description:"Darius, Xerxes, Artaxerxes, Yehud, Elephantine and the Second Temple restoration.", stories:["darius-i","xerxes","artaxerxes","yehud","elephantine","second-temple-completion"] },
  { id:"hellenistic-depth", title:"The Hellenistic World", description:"The Diadochi, Ptolemaic and Seleucid rule, Antiochus IV, the Dead Sea Scrolls and Hasmonean independence.", stories:["diadochi","ptolemaic-judea","seleucid-judea","antiochus-iv","dead-sea-scrolls","hasmonean-expansion"] },
  { id:"roman-depth", title:"Rome, Jesus and the First Jewish Revolt", description:"Pompey, Augustus, Herodian Jerusalem, John, Jesus, Paul, the Jerusalem church, the revolt, 70 CE and Masada.", stories:["pompey","augustus","herod-temple","herod-successors","john-baptist","jesus-galilee","crucifixion","resurrection-early-tradition","paul-missions","james-jerusalem","jewish-revolt","jerusalem70","masada","bar-kokhba"] },
  { id:"hellenistic-advanced", title:"Hellenistic Judea and the Maccabean Crisis", description:"The Diadochi, Ptolemaic and Seleucid transitions, Antiochus IV, Hanukkah and the Hasmonean state.", stories:["diadochi-wars","ptolemaic-administration","seleucid-transition","antiochus-iv-crisis","hanukkah-temple-rededication","hasmonean-state","hasmonean-civil-war"] },
  { id:"second-temple-society", title:"Second Temple Society and Texts", description:"Priests, sects, the Dead Sea Scrolls and the religious world surrounding the New Testament period.", stories:["second-temple-society","dead-sea-scrolls-context","jewish-sects-first-century"] },
  { id:"roman-deep-history", title:"Roman Judea and the Early Jesus Movement", description:"Roman administration, Herodian building, John the Baptist, Jesus, Paul, James and the revolts against Rome.", stories:["roman-province-judea","herodian-building-program","john-baptist-context","jesus-historical-context","paul-roman-world","jerusalem-church","jewish-revolt-causes","jerusalem-70-context","bar-kokhba-context"] },

  { id:"prophets-exile", title:"Prophets, Exile and Restoration", description:"Jeremiah, Ezekiel, Daniel, Haggai, Zechariah and Malachi across the Babylonian and Persian worlds.", stories:["jeremiah","ezekiel","daniel","haggai-zechariah","malachi"] },
  { id:"major-inscriptions", title:"Major Inscriptions and Historical Anchors", description:"The Merneptah Stele, Tel Dan Stele, Black Obelisk, Mesha Stele, Sennacherib Prism and Cyrus Cylinder.", stories:["merneptah-stele","tel-dan-stele","black-obelisk","mesha-stele","sennacherib-prism","cyrus-cylinder"] },
  { id:"roman-infrastructure", title:"Roman Infrastructure, Judaism and Historical Sources", description:"Roads, diaspora communities, synagogues, the Temple, Jewish leadership and the major literary sources for the Roman period.", stories:["roman-roads","diaspora-jews","synagogue-world","jerusalem-temple-priesthood","sanhedrin","josephus","tacitus-judea","bar-kokhba-aftermath"] }
];
