export type ExtendedScriptureBook = {
  name: string;
  slug: string;
  family: "Deuterocanonical" | "Orthodox" | "Ethiopian" | "Textual addition";
  tradition: string[];
  approximateStructure?: string;
  historicalPeriod: string;
  summary: string;
  historicalLens: string;
  connections: string[];
  notes: string[];
};

export const extendedScriptureBooks: ExtendedScriptureBook[] = [
  { name:"Tobit", slug:"tobit", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"14 chapters", historicalPeriod:"Persian-period Jewish diaspora setting", summary:"A Jewish diaspora narrative centered on Tobit, Tobias, Sarah and the angel Raphael, combining family piety, almsgiving, marriage and divine providence.", historicalLens:"Tobit is valuable for studying Jewish life, piety and diaspora imagination in the Second Temple period, while its narrative chronology and historical setting require careful distinction from independently attested events.", connections:["Assyria","Nineveh","diaspora Judaism","Raphael"], notes:["The book survives in multiple textual forms, including substantial Aramaic and Hebrew fragments from Qumran."] },
  { name:"Judith", slug:"judith", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"16 chapters", historicalPeriod:"Hellenistic-era literary setting; precise historical setting debated", summary:"A dramatic account of Judith, a Jewish heroine who saves Bethulia by entering the camp of the enemy commander Holofernes.", historicalLens:"Judith blends biblical-style storytelling with a deliberately shaped historical world; names, chronology and geography should not automatically be treated as a straightforward chronicle.", connections:["Holofernes","Bethulia","Assyrian imagery"], notes:["Its historical-literary setting is debated and is especially useful for studying Jewish resistance literature and narrative theology."] },
  { name:"Wisdom of Solomon", slug:"wisdom-of-solomon", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"19 chapters", historicalPeriod:"Hellenistic Jewish world", summary:"A wisdom work reflecting on righteousness, immortality, wisdom and the fate of the wicked.", historicalLens:"Its Greek language and engagement with the intellectual world of Hellenistic Judaism make it important for understanding Jewish thought in the centuries before Christianity.", connections:["Alexandria","Hellenistic Judaism","wisdom literature"], notes:["Traditionally associated with Solomon, but its literary setting is generally understood as much later than Solomon's reign."] },
  { name:"Sirach", slug:"sirach", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"51 chapters", historicalPeriod:"Early 2nd century BCE", summary:"Ben Sira's extensive wisdom teaching on ethics, worship, family, friendship, wisdom and Israel's ancestors.", historicalLens:"Sirach is an unusually valuable witness to Jewish wisdom and religious life in the early Hellenistic period, shortly before the Maccabean crisis.", connections:["Ben Sira","Jerusalem","Temple","wisdom literature"], notes:["The work has important Hebrew manuscript evidence and was translated into Greek by the author's grandson according to its prologue."] },
  { name:"Baruch", slug:"baruch", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"6 chapters plus Letter of Jeremiah in Catholic ordering", historicalPeriod:"Exilic and Second Temple literary horizons", summary:"A collection associated with Baruch that reflects on exile, repentance, wisdom and restoration.", historicalLens:"The book presents theological reflection through an exilic framework rather than functioning as a simple contemporary diary of the Babylonian exile.", connections:["Jeremiah","Babylon","Jerusalem","exile"], notes:["Canonical organization differs among traditions, especially around the Letter of Jeremiah."] },
  { name:"1 Maccabees", slug:"1-maccabees", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"16 chapters", historicalPeriod:"2nd century BCE", summary:"A detailed historical narrative of the Hasmonean revolt beginning with the crisis under Antiochus IV and continuing through the leadership of Judas, Jonathan and Simon.", historicalLens:"One of the most important literary sources for reconstructing the Maccabean revolt and the emergence of Hasmonean political power, while still reflecting the author's ideological perspective.", connections:["Antiochus IV","Judas Maccabaeus","Jonathan Apphus","Simon Thassi","Jerusalem","Hasmonean state"], notes:["The original Semitic form is lost; the surviving text is Greek, with evidence suggesting a Hebrew original."] },
  { name:"2 Maccabees", slug:"2-maccabees", family:"Deuterocanonical", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"15 chapters", historicalPeriod:"2nd century BCE", summary:"A theologically shaped account of the persecution under Antiochus IV, the purification of the Temple and the early Hasmonean victories.", historicalLens:"2 Maccabees is not a sequel covering the same span as 1 Maccabees; it retells an overlapping period with particular emphasis on the Temple, martyrdom, resurrection and divine justice.", connections:["Antiochus IV","Judas Maccabaeus","Temple","Jerusalem","Hasmoneans"], notes:["The work identifies itself as an abridgment of a five-volume history by Jason of Cyrene."] },
  { name:"Additions to Esther", slug:"additions-to-esther", family:"Textual addition", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"Greek additions integrated into Esther", historicalPeriod:"Hellenistic Jewish textual tradition", summary:"Greek additions to Esther expand prayers, letters, dreams and explicit references to God within the Esther narrative.", historicalLens:"The additions illuminate how later Jewish readers interpreted and expanded an earlier Hebrew narrative, making them important evidence for reception history.", connections:["Esther","Mordecai","Persian court","Ahasuerus"], notes:["Catholic and Orthodox editions incorporate the additions into Esther rather than treating them as a separate independent book."] },
  { name:"Additions to Daniel", slug:"additions-to-daniel", family:"Textual addition", tradition:["Catholic","Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"Susanna; Prayer of Azariah/Song of the Three; Bel and the Dragon", historicalPeriod:"Second Temple Jewish textual tradition", summary:"Additional Daniel narratives and liturgical material preserved prominently in Greek textual traditions.", historicalLens:"These passages demonstrate the growth of Daniel traditions and the diversity of textual forms surrounding the book in antiquity.", connections:["Daniel","Susanna","Bel","Babylon"], notes:["The additions are canonical in Catholic and Orthodox traditions but absent from the standard Protestant Old Testament."] },
  { name:"1 Esdras", slug:"1-esdras", family:"Orthodox", tradition:["Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"9 chapters", historicalPeriod:"Persian-period restoration traditions", summary:"A Greek work overlapping material from Chronicles, Ezra and Nehemiah, including the famous debate of the three guards.", historicalLens:"Its relationship to Ezra-Nehemiah and its textual history make it important for studying how Persian-period restoration traditions were transmitted and reshaped.", connections:["Zerubbabel","Ezra","Jerusalem","Second Temple"], notes:["Numbering is confusing across traditions; '1 Esdras' in one tradition is not necessarily the same work meant by that title elsewhere."] },
  { name:"3 Maccabees", slug:"3-maccabees", family:"Orthodox", tradition:["Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"7 chapters", historicalPeriod:"Hellenistic Egypt", summary:"A Jewish diaspora narrative focused on persecution and deliverance in Ptolemaic Egypt, especially under a hostile king.", historicalLens:"The narrative is a major witness to literary memory of Jewish vulnerability and divine deliverance in the Hellenistic diaspora, but its historical reconstruction is debated.", connections:["Ptolemaic Egypt","Alexandria","diaspora Judaism"], notes:["Despite its title, it does not narrate the Maccabean revolt in Judea."] },
  { name:"Psalm 151", slug:"psalm-151", family:"Orthodox", tradition:["Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"1 psalm", historicalPeriod:"Ancient Jewish psalm tradition", summary:"A short additional Davidic psalm preserved in the Septuagint tradition, reflecting on David's selection and victory.", historicalLens:"Psalm 151 is particularly important for textual history because Hebrew forms were also discovered among the Dead Sea Scrolls.", connections:["David","Psalms","Dead Sea Scrolls"], notes:["It is numbered separately from Psalms 1–150 in traditions that receive it."] },
  { name:"Prayer of Manasseh", slug:"prayer-of-manasseh", family:"Orthodox", tradition:["Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"1 prayer", historicalPeriod:"Jewish/Christian penitential tradition", summary:"A penitential prayer placed in the context of Manasseh's repentance described in 2 Chronicles 33.", historicalLens:"The prayer is best studied as a later penitential composition associated with a biblical king rather than as a securely contemporary inscription or transcript.", connections:["Manasseh","Judah","Jerusalem","repentance"], notes:["Its precise canonical status varies; some traditions place it among appendices or liturgical material."] },
  { name:"4 Maccabees", slug:"4-maccabees", family:"Orthodox", tradition:["Eastern Orthodox","Ethiopian Orthodox"], approximateStructure:"18 chapters", historicalPeriod:"Hellenistic Jewish philosophical literature", summary:"A philosophical meditation using the martyrdom narratives associated with 2 Maccabees to argue for the supremacy of reason shaped by piety.", historicalLens:"It is particularly valuable for studying the intersection of Jewish martyr traditions with Greek philosophical vocabulary.", connections:["2 Maccabees","Maccabean martyrs","Antiochus IV","Hellenistic Judaism"], notes:["Often placed in an appendix rather than treated as a core canonical book in Greek Orthodox editions."] },
  { name:"1 Enoch", slug:"1-enoch", family:"Ethiopian", tradition:["Ethiopian Orthodox"], approximateStructure:"108 chapters in the standard Ethiopic collection", historicalPeriod:"Multiple Second Temple Jewish compositional layers", summary:"A large composite collection of apocalyptic, astronomical, ethical and visionary traditions associated with Enoch.", historicalLens:"Fragments from several sections survive among the Dead Sea Scrolls, making 1 Enoch exceptionally important for understanding Second Temple Jewish apocalyptic thought.", connections:["Enoch","Watchers","Qumran","Dead Sea Scrolls","apocalyptic literature"], notes:["The work is composite; its sections were composed and transmitted across different periods rather than written as one single document at one time."] },
  { name:"Jubilees", slug:"jubilees", family:"Ethiopian", tradition:["Ethiopian Orthodox"], approximateStructure:"50 jubilees/sections", historicalPeriod:"Second Temple Judaism", summary:"A rewritten presentation of Genesis and early Exodus traditions organized around chronological jubilees and calendrical concerns.", historicalLens:"Jubilees is a major witness to Second Temple interpretation of Torah, angels, patriarchal traditions and sacred time; Hebrew fragments survive at Qumran.", connections:["Genesis","Exodus","patriarchs","Qumran","calendar"], notes:["Its importance extends well beyond canon: it is a major source for reconstructing Second Temple Jewish interpretation."] },
  { name:"1–3 Meqabyan", slug:"meqabyan", family:"Ethiopian", tradition:["Ethiopian Orthodox"], approximateStructure:"Three distinct Ethiopian works; chapter/section counting varies by edition", historicalPeriod:"Ethiopian Christian literary tradition", summary:"Three Ethiopian works traditionally grouped under the name Meqabyan; they are distinct from the Greek books called 1–3 Maccabees.", historicalLens:"They belong to a distinctive Ethiopian literary tradition and should not be retroactively equated with the Hasmonean histories of 1–3 Maccabees.", connections:["Ethiopian Orthodox","martyr traditions","Ethiopian biblical literature"], notes:["The shared English label 'Maccabees' can be misleading: Meqabyan is not simply another numbering of the Greek Maccabean books."] },
];

export const extendedBookMap = Object.fromEntries(extendedScriptureBooks.map(book => [book.slug, book]));
