import Link from "next/link";
import Header from "../../components/layout/Header";
import { evidenceItems } from "../../content/evidence";

export default async function EvidencePage({searchParams}:{searchParams?:Promise<{q?:string;type?:string}>}){
  const params=searchParams?await searchParams:{};
  const q=(params.q??"").trim().toLowerCase();
  const type=params.type??"All types";
  const types=["All types",...Array.from(new Set(evidenceItems.map(e=>e.type)))];
  const filtered=evidenceItems.filter(e=>(!q||[e.name,e.type,e.date,e.place,e.region,e.summary,e.significance,...e.themes,...e.bibleReferences].join(" ").toLowerCase().includes(q))&&(type==="All types"||e.type===type));
  return <div className="shell"><Header/><main className="mx-auto max-w-[1280px] px-5 py-10 sm:px-6 sm:py-14">
    <header className="max-w-4xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Archaeology & primary evidence</p><h1 className="mt-3 text-5xl font-semibold leading-tight sm:text-6xl">Evidence Library</h1><p className="mt-5 text-xl leading-9 text-[var(--muted)]">Inscriptions, royal records, chronicles, manuscripts, architecture and archaeological sites that help reconstruct the world behind Biblical history.</p></header>
    <div className="mt-10 grid gap-4 sm:grid-cols-3"><div className="panel rounded-2xl p-5"><p className="sans text-xs font-black uppercase tracking-widest text-[var(--muted)]">Evidence records</p><p className="mt-2 text-3xl font-semibold">{evidenceItems.length}</p><p className="mt-1 text-sm text-[var(--muted)]">curated primary/contextual sources</p></div><div className="panel rounded-2xl p-5"><p className="sans text-xs font-black uppercase tracking-widest text-[var(--muted)]">Categories</p><p className="mt-2 text-3xl font-semibold">{types.length-1}</p><p className="mt-1 text-sm text-[var(--muted)]">objects, texts & sites</p></div><div className="panel rounded-2xl p-5"><p className="sans text-xs font-black uppercase tracking-widest text-[var(--muted)]">Method</p><p className="mt-2 text-3xl font-semibold">Evidence first</p><p className="mt-1 text-sm text-[var(--muted)]">claims and limits shown separately</p></div></div>
    <form className="panel mt-10 grid gap-3 rounded-3xl p-4 sm:grid-cols-[1fr_240px_auto]" action="/evidence"><input name="q" defaultValue={params.q??""} placeholder="Search stele, scrolls, Sennacherib, Jerusalem…" className="sans rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-3 text-sm outline-none focus:border-[var(--accent)]"/><select name="type" defaultValue={type} className="sans rounded-xl border border-[var(--border)] bg-[var(--surface-2)] px-4 py-3 text-sm">{types.map(t=><option key={t}>{t}</option>)}</select><button className="sans rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-bold text-white">Filter</button></form>
    <p className="sans mt-5 text-sm font-semibold text-[var(--muted)]">Showing {filtered.length} of {evidenceItems.length} evidence records</p>
    <section className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(e=><Link key={e.slug} href={`/evidence/${e.slug}`} className="panel rounded-3xl p-5 transition hover:-translate-y-1 hover:border-[var(--accent)]"><div className="flex items-start justify-between gap-3"><p className="sans text-[10px] font-black uppercase tracking-[.16em] text-[var(--accent)]">{e.type}</p><span className="sans rounded-full bg-[var(--surface-2)] px-2.5 py-1 text-[10px] font-bold text-[var(--muted)]">{e.confidence}</span></div><h2 className="mt-3 text-2xl font-semibold">{e.name}</h2><p className="sans mt-2 text-xs font-bold text-[var(--muted)]">{e.date} · {e.place}</p><p className="mt-4 text-sm leading-7 text-[var(--muted)]">{e.summary}</p><div className="mt-4 flex flex-wrap gap-2">{e.themes.slice(0,3).map(t=><span key={t} className="sans rounded-full border border-[var(--border)] px-2.5 py-1 text-[10px] font-semibold text-[var(--muted)]">{t}</span>)}</div><span className="sans mt-5 block text-sm font-bold text-[var(--accent)]">Open evidence profile →</span></Link>)}</section>
  </main></div>
}
