import Link from "next/link";
import Header from "../../components/layout/Header";
import { bibleBooks } from "../../content/bible/books";
import { canonComparison, canonTraditions } from "../../content/bible/canons";

export default function CanonPage() {
  const extras = canonComparison.filter(row => row.category !== "shared");
  return <div className="shell"><Header/><main className="mx-auto max-w-[1500px] px-4 py-10 sm:px-6">
    <header className="max-w-5xl"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Canon & traditions</p><h1 className="mt-3 text-5xl font-semibold leading-tight">One Bible library, multiple canonical traditions</h1><p className="mt-5 text-lg leading-8 text-[var(--muted)]">The Bible Explorer now uses the 66-book Protestant canon as its core navigation set, while this section makes Catholic, Eastern Orthodox, Ethiopian Orthodox and Syriac differences explicit instead of flattening them into one list.</p></header>
    <section className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{canonTraditions.map(t=><article key={t.slug} className="panel rounded-3xl p-5"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">{t.shortName}</p><h2 className="mt-2 text-xl font-semibold">{t.bookCount} books</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{t.description}</p><dl className="sans mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-[var(--surface-2)] p-2"><dt className="text-[var(--muted)]">OT</dt><dd className="mt-1 font-bold">{t.oldTestamentCount}</dd></div><div className="rounded-xl bg-[var(--surface-2)] p-2"><dt className="text-[var(--muted)]">NT</dt><dd className="mt-1 font-bold">{t.newTestamentCount}</dd></div></dl></article>)}</section>
    <section className="mt-12 panel rounded-3xl p-6 sm:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Core library</p><h2 className="mt-2 text-3xl font-semibold">All 66 Protestant books</h2><p className="mt-2 text-[var(--muted)]">Every book is now represented in the Bible Explorer, with chapter routes generated from its chapter count.</p></div><Link href="/bible" className="sans rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-bold text-white">Open Bible Explorer →</Link></div><div className="mt-7 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{bibleBooks.map(book=><Link key={book.slug} href={`/bible?book=${book.slug}`} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] p-4 transition hover:border-[var(--accent)]"><span className="sans text-[11px] font-bold text-[var(--muted)]">{String(book.order).padStart(2,"0")} · {book.chapters} chapters</span><h3 className="mt-1 font-semibold">{book.name}</h3><p className="mt-1 text-xs text-[var(--muted)]">{book.section}</p></Link>)}</div></section>
    <section className="mt-10 panel rounded-3xl p-6 sm:p-9"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Comparison</p><h2 className="mt-2 text-3xl font-semibold">Where the traditions differ</h2><p className="mt-3 max-w-4xl text-sm leading-7 text-[var(--muted)]">The table focuses on book-level differences. Additions within Esther and Daniel are treated separately because they are additional textual material rather than simply additional book titles.</p><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[900px] border-collapse text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="p-3">Book / material</th><th className="p-3">Protestant</th><th className="p-3">Catholic</th><th className="p-3">Eastern Orthodox</th><th className="p-3">Ethiopian</th></tr></thead><tbody>{extras.map(row=><tr key={row.name} className="border-b border-[var(--border)]"><td className="p-3 font-semibold">{row.name}</td><td className="p-3">{row.protestant === "not-in-canon" ? "—" : "✓"}</td><td className="p-3">{row.catholic === "deuterocanonical" ? "Deuterocanon" : row.catholic === "not-in-canon" ? "—" : "✓"}</td><td className="p-3">{row.easternOrthodox === "received" ? "Received" : row.easternOrthodox === "appendix" ? "Appendix" : row.easternOrthodox === "not-in-canon" ? "—" : "Varies"}</td><td className="p-3">{row.ethiopianOrthodox === "canonical" ? "✓" : row.ethiopianOrthodox === "not-in-canon" ? "—" : "Varies"}</td></tr>)}</tbody></table></div></section>
    <section className="mt-10 grid gap-6 lg:grid-cols-2">{canonTraditions.slice(1).map(t=><article key={t.slug} className="panel-muted rounded-3xl p-6"><h2 className="text-xl font-semibold">{t.name}</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-[var(--muted)]">{t.notes.map(note=><li key={note}>• {note}</li>)}</ul></article>)}</section>
    <section className="mt-10 rounded-3xl bg-[var(--surface-2)] p-6"><p className="sans text-xs font-black uppercase tracking-[.16em] text-[var(--accent)]">Research note</p><p className="mt-2 text-sm leading-7 text-[var(--muted)]">Canon is not identical to manuscript tradition, translation tradition, or book order. A book can be canonical in one tradition while its placement, numbering, or textual form differs in another. This encyclopedia therefore records the tradition rather than forcing every community into the Protestant 66-book framework.</p></section>
  </main></div>;
}
