import Link from "next/link";
import { notFound } from "next/navigation";
import Header from "../../../components/layout/Header";
import { evidenceItems, evidenceMap } from "../../../content/evidence";
import { people } from "../../../content/people";
import { kingdoms } from "../../../content/kingdoms";
import { places } from "../../../content/places";

export function generateStaticParams(){ return evidenceItems.map(e=>({slug:e.slug})); }

export default async function EvidenceDetail({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const item=evidenceMap[slug];
  if(!item) notFound();
  const linkedPeople=item.people.map(s=>people.find(p=>p.slug===s)).filter(Boolean);
  const linkedKingdoms=item.kingdoms.map(s=>kingdoms.find(k=>k.slug===s)).filter(Boolean);
  const linkedPlaces=item.places.map(s=>places.find(p=>p.slug===s)).filter(Boolean);
  return <div className="shell"><Header/><main className="mx-auto max-w-[1100px] px-5 py-10 sm:px-6 sm:py-14">
    <Link href="/evidence" className="sans text-sm font-bold text-[var(--accent)]">← Evidence library</Link>
    <header className="mt-8 border-b border-[var(--border)] pb-10"><p className="sans text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">{item.type} · {item.confidence}</p><h1 className="mt-3 text-5xl font-semibold sm:text-6xl">{item.name}</h1><p className="mt-4 max-w-4xl text-xl leading-9 text-[var(--muted)]">{item.summary}</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="panel-muted rounded-2xl p-4"><p className="sans text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">Date</p><p className="mt-1 font-semibold">{item.date}</p></div><div className="panel-muted rounded-2xl p-4"><p className="sans text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">Place</p><p className="mt-1 font-semibold">{item.place}</p></div><div className="panel-muted rounded-2xl p-4"><p className="sans text-[10px] font-black uppercase tracking-widest text-[var(--muted)]">Region</p><p className="mt-1 font-semibold">{item.region}</p></div></div></header>
    <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_320px]"><article className="article"><section><h2>Why it matters</h2><p>{item.significance}</p></section><section><h2>What the evidence shows</h2><ul>{item.whatItShows.map(x=><li key={x}>{x}</li>)}</ul></section><section><h2>Limits & interpretation</h2><p>{item.limits}</p></section><section><h2>Biblical references</h2><div className="flex flex-wrap gap-2">{item.bibleReferences.map(r=><span key={r} className="sans rounded-full border border-[var(--border)] px-3 py-1.5 text-xs font-semibold">{r}</span>)}</div></section></article>
      <aside className="space-y-5"><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Connected people</h2><div className="mt-3 space-y-2">{linkedPeople.length?linkedPeople.map(p=><Link key={p!.slug} href={`/people/${p!.slug}`} className="block rounded-xl border border-[var(--border)] p-3 hover:border-[var(--accent)]"><span className="font-semibold">{p!.name}</span><span className="sans mt-1 block text-xs text-[var(--muted)]">{p!.role}</span></Link>):<p className="text-sm text-[var(--muted)]">No individual figure is directly linked.</p>}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Connected places</h2><div className="mt-3 space-y-2">{linkedPlaces.map(p=><Link key={p!.slug} href={`/places/${p!.slug}`} className="block rounded-xl border border-[var(--border)] p-3 hover:border-[var(--accent)]"><span className="font-semibold">{p!.name}</span><span className="sans mt-1 block text-xs text-[var(--muted)]">{p!.region}</span></Link>)}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Political context</h2><div className="mt-3 space-y-2">{linkedKingdoms.map(k=><Link key={k!.slug} href={`/kingdoms/${k!.slug}`} className="block rounded-xl border border-[var(--border)] p-3 hover:border-[var(--accent)]"><span className="font-semibold">{k!.name}</span><span className="sans mt-1 block text-xs text-[var(--muted)]">{k!.dates}</span></Link>)}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Related encyclopedia articles</h2><div className="mt-3 space-y-2">{item.storySlugs.map(s=><Link key={s} href={`/story/${s}`} className="block rounded-xl bg-[var(--surface-2)] p-3 text-sm font-semibold hover:text-[var(--accent)]">Open related article →</Link>)}</div></section><section className="panel rounded-3xl p-5"><h2 className="text-xl font-semibold">Themes</h2><div className="mt-3 flex flex-wrap gap-2">{item.themes.map(t=><span key={t} className="sans rounded-full border border-[var(--border)] px-3 py-1.5 text-xs font-semibold">{t}</span>)}</div></section></aside></div>
  </main></div>
}
